const AI_BASE="https://aistudio.baidu.com";
const PIPELINE_CREATE="/paddlex/v3/pipelines/sdk/create";
const PIPELINE_CALLBACK="/paddlex/v3/pipelines/sdk/create/callback";
const PIPELINE_BOSACL="/paddlex/v3/file/api/bosacl";
const PIPELINE_QUERY="/paddlex/v3/pipelines/sdk/list";
const PIPELINE_STOP="/paddlex/v3/pipelines/sdk/stop";
const MAX_JSON_BYTES=262_144;
const MAX_OUTPUT_BYTES=262_144;
const te=new TextEncoder();

function token(env){const t=String(env.BAIDU_AISTUDIO_ACCESS_TOKEN||"").trim();if(!t)throw Object.assign(new Error("BAIDU_AISTUDIO_ACCESS_TOKEN_NOT_CONFIGURED"),{status:503});return t}
const clampText=(v,n=240)=>String(v??"").slice(0,n);
function safeTaskId(v){const s=String(v||"").toLowerCase();if(!/^[a-z0-9-]{1,48}$/.test(s))throw Object.assign(new Error("BAIDU_INVALID_TASK_ID"),{status:400});return s}
async function fetchTimeout(url,init={},timeoutMs=30_000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeoutMs);try{return await fetch(url,{...init,signal:c.signal})}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("BAIDU_AISTUDIO_TIMEOUT"),{status:504});throw e}finally{clearTimeout(timer)}}
async function studioRequest(env,path,{method="POST",query=null,body=null}={}){const qs=query?canonicalQuery(query):"",url=`${AI_BASE}${path}${qs?`?${qs}`:""}`;const r=await fetchTimeout(url,{method,headers:{authorization:`token ${token(env)}`,accept:"application/json","content-type":"application/json","user-agent":"three-center-compute/2026-08"},body:body===null?undefined:JSON.stringify(body)},30_000);const raw=await r.text();if(te.encode(raw).length>MAX_JSON_BYTES)throw Object.assign(new Error("BAIDU_RESPONSE_TOO_LARGE"),{status:502});let j={};try{j=raw?JSON.parse(raw):{}}catch{throw Object.assign(new Error("BAIDU_BAD_JSON"),{status:502})}if(!r.ok)throw Object.assign(new Error(`BAIDU_HTTP_${r.status}`),{status:r.status>=400?r.status:502});return j}
function requireSuccess(j,code){if(Number(j?.errorCode)===0)return j?.result??{};throw Object.assign(new Error(`${code}:${clampText(j?.errorMsg||j?.message||"UNKNOWN")}`),{status:502,provider_code:j?.errorCode??null})}

function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function writeU16(a,o,v){a[o]=v&255;a[o+1]=(v>>>8)&255}
function writeU32(a,o,v){a[o]=v&255;a[o+1]=(v>>>8)&255;a[o+2]=(v>>>16)&255;a[o+3]=(v>>>24)&255}
function concat(...parts){const n=parts.reduce((s,p)=>s+p.length,0),out=new Uint8Array(n);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
export function zipStoreOne(name,text){const fn=te.encode(name),data=te.encode(text),crc=crc32(data);const local=new Uint8Array(30);writeU32(local,0,0x04034b50);writeU16(local,4,20);writeU16(local,6,0);writeU16(local,8,0);writeU16(local,10,0);writeU16(local,12,0);writeU32(local,14,crc);writeU32(local,18,data.length);writeU32(local,22,data.length);writeU16(local,26,fn.length);writeU16(local,28,0);const localAll=concat(local,fn,data);const central=new Uint8Array(46);writeU32(central,0,0x02014b50);writeU16(central,4,20);writeU16(central,6,20);writeU16(central,8,0);writeU16(central,10,0);writeU16(central,12,0);writeU16(central,14,0);writeU32(central,16,crc);writeU32(central,20,data.length);writeU32(central,24,data.length);writeU16(central,28,fn.length);writeU16(central,30,0);writeU16(central,32,0);writeU16(central,34,0);writeU16(central,36,0);writeU32(central,38,0);writeU32(central,42,0);const centralAll=concat(central,fn);const end=new Uint8Array(22);writeU32(end,0,0x06054b50);writeU16(end,4,0);writeU16(end,6,0);writeU16(end,8,1);writeU16(end,10,1);writeU32(end,12,centralAll.length);writeU32(end,16,localAll.length);writeU16(end,20,0);return concat(localAll,centralAll,end)}
function fixedScript(taskId){return `import json,time,hashlib\nimport paddle\nt0=time.time()\ncuda=bool(paddle.device.is_compiled_with_cuda() and paddle.device.cuda.device_count()>0)\nif not cuda: raise RuntimeError('CUDA_NOT_AVAILABLE')\npaddle.set_device('gpu:0')\npaddle.seed(20260815)\na=paddle.randn([512,512],dtype='float32')\nb=paddle.randn([512,512],dtype='float32')\nc=paddle.matmul(a,b)\npaddle.device.cuda.synchronize()\nsample=c[:16,:16].cpu().numpy()\nresult={'ok':True,'task_id':${JSON.stringify(taskId)},'provider':'baidu-aistudio','accelerator':'v100','cuda':True,'device':paddle.device.get_device(),'shape':[512,512],'checksum':hashlib.sha256(sample.tobytes()).hexdigest(),'elapsed_s':time.time()-t0}\nopen('/home/aistudio/output/three-center-result.json','w').write(json.dumps(result,sort_keys=True))\nprint('THREE_CENTER_RESULT:'+json.dumps(result,sort_keys=True))\n`}
export function fixedBundle(taskId){return zipStoreOne("run.py",fixedScript(safeTaskId(taskId)))}

function bceEncode(v){return encodeURIComponent(String(v)).replace(/[!'()*]/g,c=>`%${c.charCodeAt(0).toString(16).toUpperCase()}`)}
function bcePath(path){return bceEncode(path).replace(/%2F/gi,"/")}
function canonicalQuery(params={}){return Object.entries(params).filter(([k])=>String(k).toLowerCase()!=="authorization").map(([k,v])=>`${bceEncode(k)}=${bceEncode(v??"")}`).sort().join("&")}
function isoSeconds(d=new Date()){return d.toISOString().replace(/\.\d{3}Z$/,"Z")}
async function hmacHex(key,message){const k=await crypto.subtle.importKey("raw",te.encode(String(key)),{name:"HMAC",hash:"SHA-256"},false,["sign"]),sig=await crypto.subtle.sign("HMAC",k,te.encode(String(message)));return[...new Uint8Array(sig)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function defaultSignedHeaders(headers){return Object.keys(headers).map(x=>x.toLowerCase()).filter(x=>x==="host"||x==="content-length"||x==="content-type"||x==="content-md5"||x.startsWith("x-bce-")).sort()}
export async function bceAuthorization({ak,sk,method,path="/",query={},headers={},timestamp=isoSeconds(),expires=1800,signedHeaderNames=null}){const normalized={};for(const[k,v]of Object.entries(headers))normalized[String(k).toLowerCase()]=String(v).trim();const names=(signedHeaderNames??defaultSignedHeaders(normalized)).map(x=>String(x).toLowerCase()).sort();if(!names.includes("host"))throw new Error("BCE_HOST_MUST_BE_SIGNED");const canonicalHeaders=names.map(k=>`${bceEncode(k)}:${bceEncode(normalized[k]??"")}`).sort().join("\n"),signedHeaders=signedHeaderNames===null?"":names.join(";"),prefix=`bce-auth-v1/${ak}/${timestamp}/${expires}`,canonical=[String(method).toUpperCase(),bcePath(path||"/"),canonicalQuery(query),canonicalHeaders].join("\n"),signingKey=await hmacHex(sk,prefix),signature=await hmacHex(signingKey,canonical);return{authorization:`${prefix}/${signedHeaders}/${signature}`,timestamp,canonical,signedHeaders}}
function endpointHost(endpoint){let s=String(endpoint||"").trim();if(!s)throw new Error("BAIDU_BOS_ENDPOINT_MISSING");if(!/^https?:\/\//i.test(s))s=`https://${s}`;return new URL(s).host}
function objectPath(key){const k=String(key||"").replace(/^\/+/,"");return`/${k.split("/").map(bceEncode).join("/")}`}
async function bosRequest(sts,{method="GET",key="",query={},body=null,contentType="application/octet-stream",timeoutMs=30_000}={}){const baseHost=endpointHost(sts.endpoint),bucket=String(sts.bucketName||"").trim();if(!bucket)throw new Error("BAIDU_BOS_BUCKET_MISSING");const host=baseHost.toLowerCase().startsWith(`${bucket.toLowerCase()}.`)?baseHost:`${bucket}.${baseHost}`,path=key?objectPath(key):"/",timestamp=isoSeconds(),headersForSig={host,"x-bce-date":timestamp},auth=await bceAuthorization({ak:sts.accessKeyId,sk:sts.secretAccessKey,method,path,query,headers:headersForSig,timestamp,signedHeaderNames:["host","x-bce-date"]}),qs=canonicalQuery(query),url=`https://${host}${path}${qs?`?${qs}`:""}`,headers={authorization:auth.authorization,"x-bce-date":timestamp,"x-bce-security-token":sts.sessionToken,"content-type":contentType,"user-agent":"three-center-compute/2026-08"};return fetchTimeout(url,{method,headers,body},timeoutMs)}
function stsFromResult(r){const x={endpoint:String(r?.endpoint||""),bucketName:String(r?.bucketName||""),fileKey:String(r?.fileKey||""),accessKeyId:String(r?.accessKeyId||""),secretAccessKey:String(r?.secretAccessKey||""),sessionToken:String(r?.sessionToken||"")};if(!x.endpoint||!x.bucketName||!x.fileKey||!x.accessKeyId||!x.secretAccessKey||!x.sessionToken)throw Object.assign(new Error("BAIDU_BOS_STS_INCOMPLETE"),{status:502});return x}
async function bosAcl(env,pipelineId,source){const j=await studioRequest(env,PIPELINE_BOSACL,{method:"GET",query:{source,pipelineId}});return stsFromResult(requireSuccess(j,"BAIDU_BOSACL_FAILED"))}
async function uploadBundle(sts,bundle){const r=await bosRequest(sts,{method:"PUT",key:sts.fileKey,body:bundle,contentType:"application/zip",timeoutMs:30_000});if(!r.ok)throw Object.assign(new Error(`BAIDU_BOS_UPLOAD_HTTP_${r.status}`),{status:502})}

export async function startFixedBaiduSmoke(env,taskId){const id=safeTaskId(taskId),name=`three-center-${id}`.slice(0,64),create=await studioRequest(env,PIPELINE_CREATE,{body:{name,cmd:"python run.py",env:"paddle2.6_py3.10",device:"v100",gpus:1,payment:"coupon",dataset:[]}}),created=requireSuccess(create,"BAIDU_PIPELINE_CREATE_FAILED"),pipelineId=String(created?.pipelineId||"");if(!pipelineId)throw Object.assign(new Error("BAIDU_PIPELINE_ID_MISSING"),{status:502});try{const sts=await bosAcl(env,pipelineId,"SDK"),bundle=fixedBundle(id);await uploadBundle(sts,bundle);const cb=await studioRequest(env,PIPELINE_CALLBACK,{body:{pipelineId,success:true,fileKey:sts.fileKey,fileName:`${id}.zip`}}),done=requireSuccess(cb,"BAIDU_PIPELINE_CALLBACK_FAILED");return{ok:true,provider:"baidu-aistudio",task_id:id,pipeline_id:pipelineId,pipeline_name:name,stage:String(done?.stage||created?.stage||"submitted"),create_time:String(done?.createTime||created?.createTime||""),payment_mode:"coupon",gpus:1,device:"v100",secret_echo:false}}catch(e){await studioRequest(env,PIPELINE_CALLBACK,{body:{pipelineId,success:false,fileKey:null,fileName:null}}).catch(()=>{});throw e}}
export async function queryBaiduPipeline(env,pipelineId,name=""){const j=await studioRequest(env,PIPELINE_QUERY,{body:{pipelineId:String(pipelineId||""),pipelineName:String(name||""),stage:""}}),r=requireSuccess(j,"BAIDU_PIPELINE_QUERY_FAILED"),items=Array.isArray(r)?r:(Array.isArray(r?.list)?r.list:[]),hit=items.find(x=>String(x?.pipelineId||"")===String(pipelineId))||items[0]||null;return{ok:true,provider:"baidu-aistudio",found:Boolean(hit),pipeline_id:String(hit?.pipelineId||pipelineId||""),pipeline_name:String(hit?.pipelineName||name||""),stage:String(hit?.stage||"unknown"),create_time:String(hit?.createTime||""),secret_echo:false}}
export async function stopBaiduPipeline(env,pipelineId){const j=await studioRequest(env,PIPELINE_STOP,{body:{pipelineId:String(pipelineId||"")}});requireSuccess(j,"BAIDU_PIPELINE_STOP_FAILED");return{ok:true,provider:"baidu-aistudio",pipeline_id:String(pipelineId||""),stopped:true,secret_echo:false}}
function xmlDecode(s){return String(s||"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&")}
async function listOutputKeys(sts){const prefix=String(sts.fileKey||"").replace(/^\/+/,"").replace(/\/?$/,"/"),r=await bosRequest(sts,{method:"GET",query:{prefix,maxKeys:"1000"},body:null,contentType:"application/octet-stream",timeoutMs:30_000});if(!r.ok)throw Object.assign(new Error(`BAIDU_BOS_LIST_HTTP_${r.status}`),{status:502});const xml=await r.text();return[...xml.matchAll(/<Key>([\s\S]*?)<\/Key>/g)].map(m=>xmlDecode(m[1]))}
export async function getFixedBaiduResult(env,pipelineId){const sts=await bosAcl(env,String(pipelineId||""),"customCodeOutput"),keys=await listOutputKeys(sts),key=keys.find(k=>/(^|\/)three-center-result\.json$/i.test(k));if(!key)throw Object.assign(new Error("BAIDU_RESULT_FILE_NOT_FOUND"),{status:404});const r=await bosRequest(sts,{method:"GET",key,body:null,contentType:"application/octet-stream",timeoutMs:30_000});if(!r.ok)throw Object.assign(new Error(`BAIDU_RESULT_HTTP_${r.status}`),{status:502});const raw=await r.text();if(te.encode(raw).length>MAX_OUTPUT_BYTES)throw Object.assign(new Error("BAIDU_RESULT_TOO_LARGE"),{status:502});let result;try{result=JSON.parse(raw)}catch{throw Object.assign(new Error("BAIDU_RESULT_BAD_JSON"),{status:502})}return{ok:true,provider:"baidu-aistudio",pipeline_id:String(pipelineId||""),result,secret_echo:false}}
export const baiduNativeMeta=()=>({transport:"aistudio-sdk-compatible-pipeline",pipeline_api_base:AI_BASE,device:"v100",gpus:1,payment_mode:"coupon",acoin_allowed:false,paid_fallback:false,fixed_bundle_only:true,arbitrary_code:false,bos_upload:"sts-bce-v1",route_eligible:false,acceptance_required:true});