const TOKEN_URL="https://oauth2.googleapis.com/token";
const EE_BASE="https://earthengine.googleapis.com/v1";
const b64u=s=>btoa(String.fromCharCode(...new Uint8Array(s))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
const enc=s=>new TextEncoder().encode(s);
function pemToBuf(pem){const b64=String(pem||"").replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s+/g,"");if(!b64)throw new Error("GOOGLE_EE_PRIVATE_KEY_MISSING");const raw=atob(b64),a=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)a[i]=raw.charCodeAt(i);return a.buffer}
function cfg(env){const eeRaw=env.GOOGLE_EE_SERVICE_ACCOUNT_JSON,cloudRaw=env.GOOGLE_CLOUD_CREDENTIALS,raw=eeRaw||cloudRaw,credentialSource=eeRaw?"google-ee-specific":cloudRaw?"google-cloud-standard":null,eeProject=String(env.GOOGLE_EE_PROJECT_ID||"").trim(),cloudProject=String(env.GOOGLE_CLOUD_PROJECT||"").trim();if(!raw)return{configured:false,credential_source:null,project_configured:Boolean(eeProject||cloudProject),service_account_configured:false};let sa;try{sa=typeof raw==="string"?JSON.parse(raw):raw}catch{throw new Error("GOOGLE_EE_SERVICE_ACCOUNT_JSON_INVALID")};if(!sa?.client_email||!sa?.private_key)throw new Error("GOOGLE_EE_SERVICE_ACCOUNT_FIELDS_MISSING");const embedded=String(sa?.project_id||"").trim(),project=eeProject||cloudProject||embedded,projectSource=eeProject?"google-ee-env":cloudProject?"google-cloud-env":"service-account-json";if(!project)return{configured:false,credential_source:credentialSource,project_configured:false,project_embedded:false,service_account_configured:true};return{configured:true,project,project_source:projectSource,credential_source:credentialSource,project_embedded:Boolean(embedded),sa}}
async function accessToken(env){const c=cfg(env);if(!c.configured)return c;const now=Math.floor(Date.now()/1000),header=b64u(enc(JSON.stringify({alg:"RS256",typ:"JWT"}))),payload=b64u(enc(JSON.stringify({iss:c.sa.client_email,scope:"https://www.googleapis.com/auth/earthengine",aud:c.sa.token_uri||TOKEN_URL,iat:now,exp:now+3600}))),unsigned=`${header}.${payload}`;const key=await crypto.subtle.importKey("pkcs8",pemToBuf(c.sa.private_key),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]),sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,enc(unsigned)),assertion=`${unsigned}.${b64u(sig)}`;const r=await fetch(c.sa.token_uri||TOKEN_URL,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded",accept:"application/json"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion}).toString()});const j=await r.json().catch(()=>({}));if(!r.ok||!j.access_token)throw Object.assign(new Error("GOOGLE_EE_OAUTH_FAILED"),{status:r.status});return{...c,token:j.access_token}}
function headers(a){return{authorization:`Bearer ${a.token}`,accept:"application/json"}}
async function configState(a){const r=await fetch(`${EE_BASE}/projects/${encodeURIComponent(a.project)}/config`,{headers:headers(a)}),j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error("GOOGLE_EE_CONFIG_FAILED"),{status:r.status});return String(j?.registrationState||"UNKNOWN")}
async function computeExpression(a,expression,tag){const r=await fetch(`${EE_BASE}/projects/${encodeURIComponent(a.project)}/value:compute`,{method:"POST",headers:{...headers(a),"content-type":"application/json"},body:JSON.stringify({expression,workloadTag:tag})}),j=await r.json().catch(()=>({}));return{ok:r.ok,status:r.status,result:j?.result,error:j?.error||null}}
const constantExpression=value=>({values:{answer:{constantValue:value}},result:"answer"});
export async function probeEarthEngine(env,{compute=false}={}){const a=await accessToken(env);if(!a.configured)return{ok:false,configured:false,credential_source:a.credential_source||null,project_configured:a.project_configured,project_embedded:a.project_embedded===true,service_account_configured:a.service_account_configured,secret_echo:false};const registrationState=await configState(a);let computeOk=null;if(compute){const r=await computeExpression(a,constantExpression(42),"three-center-smoke");if(!r.ok)throw Object.assign(new Error("GOOGLE_EE_COMPUTE_FAILED"),{status:r.status});computeOk=Number(r.result)===42}return{ok:true,configured:true,credential_source:a.credential_source,project_source:a.project_source,project_embedded:a.project_embedded===true,oauth:true,registration_state:registrationState,compute_requested:compute,compute_ok:computeOk,result_is_42:computeOk,secret_echo:false}}
export async function stressEarthEngine(env){const a=await accessToken(env);if(!a.configured)throw Object.assign(new Error("GOOGLE_EE_NOT_CONFIGURED"),{status:503});const registrationState=await configState(a),start=Date.now(),count=24;const burst=await Promise.all(Array.from({length:count},(_,i)=>computeExpression(a,constantExpression(i),`three-center-burst-${i}`)));const burstOk=burst.every((r,i)=>r.ok&&Number(r.result)===i),statuses=[...new Set(burst.map(r=>r.status))].sort((x,y)=>x-y);
  const geoExpression={values:{image:{functionInvocationValue:{functionName:"Image.load",arguments:{id:{constantValue:"CGIAR/SRTM90_V4"}}}},ten:{functionInvocationValue:{functionName:"Image.constant",arguments:{value:{constantValue:10}}}},added:{functionInvocationValue:{functionName:"Image.add",arguments:{image1:{valueReference:"image"},image2:{valueReference:"ten"}}}}},result:"added"};
  const geo=await computeExpression(a,geoExpression,"three-center-geospatial-smoke"),geoOk=geo.ok&&geo.result&&typeof geo.result==="object";
  const invalid=await computeExpression(a,{values:{},result:"missing"},"three-center-negative-test"),negativeOk=!invalid.ok&&invalid.status>=400&&invalid.status<500;
  return{ok:burstOk&&geoOk&&negativeOk,credential_source:a.credential_source,project_source:a.project_source,registration_state:registrationState,parallel_requests:count,parallel_all_correct:burstOk,parallel_http_statuses:statuses,geospatial_asset:"CGIAR/SRTM90_V4",geospatial_graph_ok:geoOk,negative_request_rejected:negativeOk,negative_http_status:invalid.status,elapsed_ms:Date.now()-start,secret_echo:false}}
