const TOKEN_URL="https://oauth2.googleapis.com/token";
const EE_BASE="https://earthengine.googleapis.com/v1";
const b64u=s=>btoa(String.fromCharCode(...new Uint8Array(s))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
const enc=s=>new TextEncoder().encode(s);
function pemToBuf(pem){const b64=String(pem||"").replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s+/g,"");if(!b64)throw new Error("GOOGLE_EE_PRIVATE_KEY_MISSING");const raw=atob(b64),a=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)a[i]=raw.charCodeAt(i);return a.buffer}
function cfg(env){const project=String(env.GOOGLE_EE_PROJECT_ID||"").trim(),raw=env.GOOGLE_EE_SERVICE_ACCOUNT_JSON;if(!project||!raw)return{configured:false,project_configured:Boolean(project),service_account_configured:Boolean(raw)};let sa;try{sa=typeof raw==="string"?JSON.parse(raw):raw}catch{throw new Error("GOOGLE_EE_SERVICE_ACCOUNT_JSON_INVALID")};if(!sa?.client_email||!sa?.private_key)throw new Error("GOOGLE_EE_SERVICE_ACCOUNT_FIELDS_MISSING");return{configured:true,project,sa}}
async function accessToken(env){const c=cfg(env);if(!c.configured)return c;const now=Math.floor(Date.now()/1000),header=b64u(enc(JSON.stringify({alg:"RS256",typ:"JWT"}))),payload=b64u(enc(JSON.stringify({iss:c.sa.client_email,scope:"https://www.googleapis.com/auth/earthengine",aud:c.sa.token_uri||TOKEN_URL,iat:now,exp:now+3600}))),unsigned=`${header}.${payload}`;const key=await crypto.subtle.importKey("pkcs8",pemToBuf(c.sa.private_key),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]),sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,enc(unsigned)),assertion=`${unsigned}.${b64u(sig)}`;const r=await fetch(c.sa.token_uri||TOKEN_URL,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded",accept:"application/json"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion}).toString()});const j=await r.json().catch(()=>({}));if(!r.ok||!j.access_token)throw Object.assign(new Error("GOOGLE_EE_OAUTH_FAILED"),{status:r.status});return{...c,token:j.access_token}}
export async function probeEarthEngine(env,{compute=false}={}){const a=await accessToken(env);if(!a.configured)return{ok:false,configured:false,project_configured:a.project_configured,service_account_configured:a.service_account_configured,secret_echo:false};const h={authorization:`Bearer ${a.token}`,accept:"application/json"};const cr=await fetch(`${EE_BASE}/projects/${encodeURIComponent(a.project)}/config`,{headers:h}),cj=await cr.json().catch(()=>({}));if(!cr.ok)throw Object.assign(new Error("GOOGLE_EE_CONFIG_FAILED"),{status:cr.status});let computeOk=null,result=null;if(compute){const rr=await fetch(`${EE_BASE}/projects/${encodeURIComponent(a.project)}/value:compute`,{method:"POST",headers:{...h,"content-type":"application/json"},body:JSON.stringify({expression:{values:{answer:{constantValue:42}},result:"answer"},workloadTag:"three-center-smoke"})}),rj=await rr.json().catch(()=>({}));if(!rr.ok)throw Object.assign(new Error("GOOGLE_EE_COMPUTE_FAILED"),{status:rr.status});result=rj?.result;computeOk=Number(result)===42}
return{ok:true,configured:true,oauth:true,registration_state:String(cj?.registrationState||"UNKNOWN"),compute_requested:compute,compute_ok:computeOk,result_is_42:computeOk,secret_echo:false}}
