import base,{CenterGate as BaseCenterGate} from "./index.js";
import {getStatus,getOutput,removeKernel,introspect} from "./kaggle-official.js";
import {cancelKernel,probeMcp} from "./kaggle-mcp.js";
const MAX_LEASE_SECONDS=7200;
const AUTH_CIRCUIT_COOLDOWN_MS=300000,AUTH_CIRCUIT_INFLIGHT_MS=30000;
const INTERNAL_ONLY=new Set(["/v1/run","/v1/status","/v1/cancel","/v1/selftest"]);
const json=(x,s=200)=>Response.json(x,{status:s,headers:{"cache-control":"no-store"}});
const err=(c,m,s=400,d)=>json({ok:false,error:c,message:m,...(d?{details:d}:{})},s);
export class CenterGate{constructor(state,env){this.state=state;this.inner=new BaseCenterGate(state,env)}async fetch(req){const u=new URL(req.url),m=u.pathname.match(/^\/auth-circuit\/([a-z0-9-]{1,64})\/(state|acquire|result)$/);if(m){const provider=m[1],action=m[2],storage=this.state.storage,key=`auth-circuit:${provider}`,now=Date.now(),old=await storage.get(key)||{},cooldownUntil=Number(old.cooldown_until_ms||0),inflightUntil=Number(old.inflight_until_ms||0),cooldownActive=cooldownUntil>now,inflightActive=inflightUntil>now;if(req.method==="GET"&&action==="state")return json({ok:true,provider,cooldown_active:cooldownActive,cooldown_remaining_ms:cooldownActive?cooldownUntil-now:0,probe_inflight:inflightActive,probe_remaining_ms:inflightActive?inflightUntil-now:0,upstream_allowed:!cooldownActive&&!inflightActive,secrets_redacted:true});if(req.method==="POST"&&action==="acquire"){if(cooldownActive)return json({ok:false,error:"AUTH_COOLDOWN",provider,cooldown_active:true,cooldown_remaining_ms:cooldownUntil-now,probe_inflight:false,upstream_allowed:false,secrets_redacted:true},429);if(inflightActive)return json({ok:false,error:"AUTH_PROBE_INFLIGHT",provider,cooldown_active:false,cooldown_remaining_ms:0,probe_inflight:true,probe_remaining_ms:inflightUntil-now,upstream_allowed:false,secrets_redacted:true},409);const attemptId=crypto.randomUUID(),rec={provider,attempt_id:attemptId,inflight_until_ms:now+AUTH_CIRCUIT_INFLIGHT_MS,cooldown_until_ms:0,updated_at:new Date(now).toISOString()};await storage.put(key,rec);return json({ok:true,provider,attempt_id:attemptId,cooldown_active:false,probe_inflight:true,probe_remaining_ms:AUTH_CIRCUIT_INFLIGHT_MS,upstream_allowed:true,secrets_redacted:true})}if(req.method==="POST"&&action==="result"){const b=await req.json().catch(()=>({})),attemptId=String(b.attempt_id||"");if(!attemptId||attemptId!==String(old.attempt_id||""))return json({ok:false,error:"AUTH_PROBE_OWNER_MISMATCH",provider,upstream_allowed:false,secrets_redacted:true},409);const authFailed=b.auth_failed===true,nextCooldown=authFailed?now+AUTH_CIRCUIT_COOLDOWN_MS:0;await storage.put(key,{provider,attempt_id:null,inflight_until_ms:0,cooldown_until_ms:nextCooldown,last_auth_failed:authFailed,updated_at:new Date(now).toISOString()});return json({ok:true,provider,auth_failed:authFailed,cooldown_active:authFailed,cooldown_remaining_ms:authFailed?AUTH_CIRCUIT_COOLDOWN_MS:0,probe_inflight:false,upstream_allowed:!authFailed,secrets_redacted:true})}return json({ok:false,error:"AUTH_CIRCUIT_METHOD_NOT_ALLOWED"},405)}if(req.method==="POST"&&u.pathname==="/acquire"){const b=await req.clone().json().catch(()=>({})),requested=Number(b.lease_seconds||0),leaseSeconds=Math.max(300,Math.min(MAX_LEASE_SECONDS,(Number.isFinite(requested)?Math.trunc(requested):300)+180));req=new Request(req.url,{method:"POST",headers:req.headers,body:JSON.stringify({...b,lease_seconds:leaseSeconds})})}return this.inner.fetch(req)}}
function gate(env){return env.CENTER_GATE.get(env.CENTER_GATE.idFromName("global"))}
async function g(env,p,m="GET",b){const i={method:m,headers:{"content-type":"application/json"}};if(b!==undefined)i.body=JSON.stringify(b);const r=await gate(env).fetch(new Request(`https://gate.internal${p}`,i));return{http:r.status,...await r.json().catch(()=>({ok:false,error:"GATE_BAD_RESPONSE"}))}}
async function load(env,id){return g(env,`/task/${encodeURIComponent(id)}`)}async function save(env,id,p){return g(env,`/task/${encodeURIComponent(id)}`,"POST",p)}async function release(env,id){return g(env,"/release","POST",{task_id:id})}
function terminalStored(s){return["completed","failed","cancelled"].includes(String(s||""))}
export function normalizeModelRecipeResult(task,result){
  if(task?.kind!=="model-recipe"||!result||typeof result!=="object")return result;
  if(result.kind==="model-recipe")return result;
  const taskId=String(task.task_id||""),modelId=String(task.model_id||""),recipe=String(task.recipe||""),method=String(task.method||"");
  const identityOk=result.ok===true&&String(result.task_id||"")===taskId&&String(result.model_id||"")===modelId&&String(result.recipe||"")===recipe&&String(result.method||"")===method;
  const executionOk=task.gpu===false&&String(task.machine_shape||"").toLowerCase()==="cpu"&&result.network_used===false&&result.arbitrary_code===false;
  if(!identityOk||!executionOk)return result;
  return{ok:true,kind:"model-recipe",task_id:taskId,profile:String(task.profile||"model"),model_id:modelId,method,recipe,accelerator:"cpu",result};
}
function validResult(task,result){if(!result||result.ok!==true||String(result.task_id)!==String(task.task_id)||String(result.profile)!==String(task.profile))return{ok:false,reason:"RESULT_IDENTITY_MISMATCH"};if(task.kind==="model-recipe"){if(result.kind!=="model-recipe"||String(result.model_id)!==String(task.model_id))return{ok:false,reason:"MODEL_RECIPE_IDENTITY_MISMATCH"};if(result.accelerator!=="cpu")return{ok:false,reason:"MODEL_RECIPE_CPU_REQUIRED"};if(!result.recipe||String(result.recipe)!==String(task.recipe)||String(result.method||"")!==String(task.method||"")||result.result===undefined||result.result===null)return{ok:false,reason:"MODEL_RECIPE_RESULT_MISSING"};return{ok:true,kind:"model-recipe",model_id:task.model_id,recipe:String(result.recipe),method:String(result.method),result_envelope:"canonical-model-recipe"}}if(task.gpu){if(result.accelerator!=="t4"||result.cuda!==true||!/t4/i.test(String(result.device||"")))return{ok:false,reason:"T4_VERIFICATION_FAILED"};if(Number(result.relative_error)>0.05)return{ok:false,reason:"GPU_CPU_CONSISTENCY_FAILED"}}else{if(result.accelerator!=="cpu")return{ok:false,reason:"CPU_VERIFICATION_FAILED"};if(!(Number(result.pi)>3.10&&Number(result.pi)<3.18))return{ok:false,reason:"MONTE_CARLO_SANITY_FAILED"};if(Number(result.linear_residual)>1e-6)return{ok:false,reason:"LINEAR_SOLVE_SANITY_FAILED"}}return{ok:true}}
async function sha256(v){const h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(String(v||"")));return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function retrievalMeta(out){return{source:out?.result_source||null,marker_present:out?.marker_present===true,file_count:Array.isArray(out?.files)?out.files.length:0,file_names:Array.isArray(out?.files)?out.files.slice(0,20).map(x=>String(x?.file_name||"").slice(0,160)):[]}}
async function finish(env,id,task,status,failure=""){let result=null,logDigest=null,resultDigest=null,cleanup=false,verification={ok:false,reason:"NOT_COMPLETED"},outputRetrieval={source:null,marker_present:false,file_count:0,file_names:[]};try{if(status==="completed"){const out=await getOutput(env,task);result=normalizeModelRecipeResult(task,out.result);logDigest=out.log_digest;outputRetrieval=retrievalMeta(out);if(!result){verification={ok:false,reason:"OUTPUT_RESULT_MISSING"};status="failed"}else{verification=validResult(task,result);if(!verification.ok)status="failed";else resultDigest=await sha256(JSON.stringify(result))}}}catch(e){status="failed";failure=String(e?.message||e);verification={ok:false,reason:"OUTPUT_RETRIEVAL_FAILED"}}cleanup=await removeKernel(env,task).catch(()=>false);await save(env,id,{status,error:status==="failed"?(failure||verification.reason):null,result_digest:resultDigest,log_digest:logDigest,verification,output_retrieval:outputRetrieval,temporary_kernel_deleted:cleanup,finished_at:new Date().toISOString()});await release(env,id);if(status==="completed")return json({ok:true,task_id:id,status,result,result_digest:resultDigest,verification,output_retrieval:outputRetrieval,temporary_kernel_deleted:cleanup});if(status==="cancelled")return json({ok:true,task_id:id,status,temporary_kernel_deleted:cleanup});return err("UPSTREAM_TASK_FAILED",failure||verification.reason||"Kaggle task failed",502,{task_id:id,verification,output_retrieval:outputRetrieval,temporary_kernel_deleted:cleanup})}
async function status(req,env){const b=await req.json().catch(()=>({})),id=String(b.task_id||"");if(!id)return err("INVALID_REQUEST","task_id required",400);const t=await load(env,id),task=t.task;if(!task)return err("TASK_NOT_FOUND","Task not found",404);if(terminalStored(task.status))return json({ok:task.status!=="failed",task_id:id,status:task.status,result_digest:task.result_digest||null,log_digest:task.log_digest||null,verification:task.verification||null,output_retrieval:task.output_retrieval||null,temporary_kernel_deleted:task.temporary_kernel_deleted===true,finished_at:task.finished_at||null});if(!task.user_name||!task.kernel_slug)return err("TASK_NOT_READY","Kaggle task metadata is incomplete",409,{task_id:id});try{const s=await getStatus(env,task);if(["queued","running","cancel_requested"].includes(s.status)){await save(env,id,{status:s.status,kaggle_failure_message:s.failure_message||null,last_polled_at:new Date().toISOString()});return json({ok:true,task_id:id,status:s.status,lock_released:false},202)}if(s.status==="completed")return await finish(env,id,task,"completed",s.failure_message);if(s.status==="cancelled")return await finish(env,id,task,"cancelled",s.failure_message);return await finish(env,id,task,"failed",s.failure_message||"Kaggle reported ERROR")}catch(e){return err(e?.message||"UPSTREAM_UNAVAILABLE","Kaggle official status failed; lock retained",e?.status||502,{task_id:id,lock_retained:true})}}
async function cancel(req,env){const b=await req.json().catch(()=>({})),id=String(b.task_id||"");if(!id)return err("INVALID_REQUEST","task_id required",400);const t=await load(env,id),task=t.task;if(!task)return err("TASK_NOT_FOUND","Task not found",404);if(terminalStored(task.status))return json({ok:true,task_id:id,status:task.status,lock_retained:false});await g(env,`/task/${encodeURIComponent(id)}/cancel`,"POST",{});try{const r=await cancelKernel(env,task);await save(env,id,{status:"cancel_requested",cancel_dispatch_ok:true,cancel_transport:"kaggle-official-mcp",cancel_tool:r.tool,cancel_requested_at:new Date().toISOString()});return json({ok:true,task_id:id,status:"cancel_requested",lock_retained:true,transport:"kaggle-official-mcp"},202)}catch(e){await save(env,id,{cancel_dispatch_ok:false,cancel_error:String(e?.message||e)});return err(e?.message||"KAGGLE_CANCEL_FAILED","Kaggle cancel failed; lock retained",e?.status||502,{task_id:id,lock_retained:true})}}
async function selftest(env){try{const who=await introspect(env),mcp=await probeMcp(env),ok=who.active===true&&mcp.ok===true&&mcp.notebook_tools>0;return json({ok,selftest_level:"live-control-plane",business_e2e:false,service:"compute-worker",executor:"kaggle-official",token_active:who.active===true,username_resolved:Boolean(who.username),mcp_authenticated:mcp.ok===true,mcp_tools_count:mcp.tools_count,mcp_notebook_tools:mcp.notebook_tools,mcp_cancel_tool_present:mcp.cancel_tool_present,bridge_required:false},ok?200:503)}catch(e){return err(e?.message||"KAGGLE_SELFTEST_FAILED","Kaggle live control-plane selftest failed",e?.status||503,{business_e2e:false})}}
export default{async fetch(req,env,ctx){try{const u=new URL(req.url);if(req.method==="POST"&&INTERNAL_ONLY.has(u.pathname)&&u.hostname!=="compute.internal")return err("POLICY_DENIED","compute execution routes are service-binding internal only",403);if(req.method==="POST"&&u.pathname==="/v1/status")return await status(req,env);if(req.method==="POST"&&u.pathname==="/v1/cancel")return await cancel(req,env);if(req.method==="POST"&&u.pathname==="/v1/selftest")return await selftest(env);return await base.fetch(req,env,ctx)}catch(e){return err(e?.message||"INTERNAL_ERROR","Request failed",e?.status||500,e?.details)}}};