import base,{CenterGate} from "./index.js";
export {CenterGate};
const json=(x,s=200)=>Response.json(x,{status:s,headers:{"cache-control":"no-store"}});
const err=(c,m,s=400,d)=>json({ok:false,error:c,message:m,...(d?{details:d}:{})},s);
function gate(env){return env.CENTER_GATE.get(env.CENTER_GATE.idFromName("global"))}
async function g(env,p,m="GET",b){const i={method:m,headers:{"content-type":"application/json"}};if(b!==undefined)i.body=JSON.stringify(b);const r=await gate(env).fetch(new Request(`https://gate.internal${p}`,i));return{http:r.status,...await r.json().catch(()=>({ok:false,error:"GATE_BAD_RESPONSE"}))}}
async function load(env,id){return g(env,`/task/${encodeURIComponent(id)}`)}
async function save(env,id,p){return g(env,`/task/${encodeURIComponent(id)}`,"POST",p)}
async function release(env,id){return g(env,"/release","POST",{task_id:id})}
function safeRemote(env,value){try{if(!value||!env.KAGGLE_MCP_BRIDGE_URL)return null;const u=new URL(value),b=new URL(env.KAGGLE_MCP_BRIDGE_URL);return u.protocol==="https:"&&u.origin===b.origin?u.toString():null}catch{return null}}
function auth(env){return env.KAGGLE_MCP_AUTH?{authorization:`Bearer ${env.KAGGLE_MCP_AUTH}`,accept:"application/json"}:{accept:"application/json"}}
function terminal(x){const s=String(x?.status||x?.state||"").toLowerCase();return x?.terminal===true||x?.done===true||x?.finished===true||["completed","complete","succeeded","success","failed","failure","cancelled","canceled","error","finished","done"].includes(s)}
function normalized(x){const s=String(x?.status||x?.state||"").toLowerCase();if(["failed","failure","error"].includes(s))return"failed";if(["cancelled","canceled"].includes(s))return"cancelled";if(terminal(x))return"completed";return"running"}
async function upstream(url,init,ms=8000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{...init,signal:c.signal});const x=await r.json().catch(()=>null);return{ok:r.ok,status:r.status,body:x}}finally{clearTimeout(t)}}
async function cancel(req,env){const b=await req.json().catch(()=>({})),id=String(b.task_id||"");if(!id)return err("INVALID_REQUEST","task_id required",400);const t=await load(env,id);if(!t.task)return err("INVALID_REQUEST","Task not found",404);const marked=await g(env,`/task/${encodeURIComponent(id)}/cancel`,"POST",{});const raw=t.task.remote_cancel_url,safe=safeRemote(env,raw);if(raw&&!safe){await save(env,id,{cancel_dispatch_ok:false,error:"POLICY_DENIED",message:"remote_cancel_url is outside Kaggle bridge origin"});return err("POLICY_DENIED","Unsafe remote cancel URL rejected; lock retained",403,{task_id:id,lock_retained:true})}if(!safe)return json({ok:marked.ok,task:marked.task||t.task,cancellation_pending:true,lock_retained:true},202);try{const r=await upstream(safe,{method:"POST",headers:auth(env)});const isTerminal=terminal(r.body);await save(env,id,{cancel_dispatch_ok:r.ok,cancel_dispatch_http_status:r.status,cancellation_pending:!isTerminal,...(isTerminal?{status:"cancelled",finished_at:new Date().toISOString()}:{})});if(isTerminal)await release(env,id);return json({ok:r.ok,task_id:id,cancellation_pending:!isTerminal,lock_retained:!isTerminal,upstream_status:r.status},r.ok?202:502)}catch(e){await save(env,id,{cancel_dispatch_ok:false,cancellation_pending:true,cancel_error:String(e?.message||e)});return err("UPSTREAM_UNAVAILABLE","Kaggle cancel dispatch failed; lock retained",502,{task_id:id,lock_retained:true})}}
async function status(req,env){const b=await req.json().catch(()=>({})),id=String(b.task_id||"");if(!id)return err("INVALID_REQUEST","task_id required",400);const t=await load(env,id);if(!t.task)return err("INVALID_REQUEST","Task not found",404);const raw=t.task.remote_status_url,safe=safeRemote(env,raw);if(raw&&!safe)return err("POLICY_DENIED","Unsafe remote status URL rejected",403,{task_id:id});if(!safe)return json({ok:true,task:t.task});try{const r=await upstream(safe,{headers:auth(env)});if(!r.ok)return err("UPSTREAM_UNAVAILABLE","Kaggle bridge status failed",502,{task:t.task,upstream_status:r.status});const done=terminal(r.body),st=normalized(r.body);if(done){await save(env,id,{status:st,upstream_terminal:true,finished_at:new Date().toISOString()});await release(env,id)}return json({ok:true,task:{...t.task,...(done?{status:st,upstream_terminal:true}:{})},upstream:r.body,upstream_status:r.status,lock_released:done})}catch(e){return err("UPSTREAM_UNAVAILABLE","Kaggle bridge status failed",502,{task:t.task})}}
export default{async fetch(req,env,ctx){try{const u=new URL(req.url);if(req.method==="POST"&&u.pathname==="/v1/cancel")return await cancel(req,env);if(req.method==="POST"&&u.pathname==="/v1/status")return await status(req,env);return await base.fetch(req,env,ctx)}catch(e){return err(e?.message||"INTERNAL_ERROR","Request failed",e?.status||500)}}};
