import guard,{CenterGate} from "./guard.js";
import {probeMcp} from "./kaggle-mcp.js";
import {probePushSchema} from "./kaggle-mcp-schema.js";
import {probeEarthEngine,stressEarthEngine} from "./google-ee.js";
export {CenterGate};
const PATH="/__diag/kaggle-live-41d820f5-4211-47dc-bf08-0b5316d602ae";
const EXPIRES=Date.parse("2026-08-15T06:00:00Z");
const json=(x,s=200)=>Response.json(x,{status:s,headers:{"cache-control":"no-store"}});
async function rpcRoutes(env){const token=String(env.KAGGLE_API_TOKEN||"").trim();if(!token)return{ok:false,token_configured:false,secret_echo:false};const call=async method=>{const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(`https://api.kaggle.com/v1/kernels.KernelsApiService/${method}`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json",accept:"application/json"},body:"{}",signal:c.signal});try{await r.body?.cancel()}catch{}return r.status}catch{return 0}finally{clearTimeout(t)}};const save=await call("SaveKernel"),status=await call("GetKernelSessionStatus");return{ok:true,token_configured:true,save_kernel_status:save,get_status_status:status,save_route_exists:save!==404&&save!==0,status_route_exists:status!==404&&status!==0,secret_echo:false}}
export default{async fetch(req,env,ctx){const u=new URL(req.url);if(req.method==="POST"&&u.pathname===PATH){const b=await req.clone().json().catch(()=>({}));const action=String(b.action||"");if(Date.now()>EXPIRES)return json({ok:false,error:"DIAG_EXPIRED"},410);if(action==="mcp_capability"){try{const m=await probeMcp(env);return json({ok:m.ok===true,tools_count:m.tools_count,notebook_tools:m.notebook_tools,push_tool_present:m.push_tool_present===true,push_accepts_gpu:m.push_accepts_gpu===true,session_create_present:m.session_create_present===true,session_accepts_gpu:m.session_accepts_gpu===true,cancel_tool_present:m.cancel_tool_present===true,secret_echo:false})}catch(e){return json({ok:false,error_class:String(e?.message||"").startsWith("KAGGLE_MCP_")?"mcp":"other",http_status:Number(e?.status||0)||null,secret_echo:false},503)}}if(action==="mcp_push_schema"){try{const s=await probePushSchema(env);return json({...s,secret_echo:false},s.ok?200:503)}catch(e){return json({ok:false,error_class:String(e?.message||"").startsWith("KAGGLE_MCP_")?"mcp":"other",http_status:Number(e?.status||0)||null,secret_echo:false},503)}}if(action==="kaggle_rpc_routes")return json(await rpcRoutes(env),200);if(action==="google_ee_probe"||action==="google_ee_compute"){try{const p=await probeEarthEngine(env,{compute:action==="google_ee_compute"});return json(p,200)}catch(e){return json({ok:false,configured:true,error_class:String(e?.message||"GOOGLE_EE_FAILED"),http_status:Number(e?.status||0)||null,secret_echo:false},200)}}if(action==="google_ee_stress"){try{return json(await stressEarthEngine(env),200)}catch(e){return json({ok:false,error_class:String(e?.message||"GOOGLE_EE_STRESS_FAILED"),http_status:Number(e?.status||0)||null,secret_echo:false},200)}}}return guard.fetch(req,env,ctx)}};