import {dispatch,officialMeta} from "./kaggle-official.js";
import {baiduAIStudioMeta} from "./baidu-aistudio.js";
import {openEOMeta} from "./openeo.js";
import {queryWolfram,wolframMeta} from "./wolfram.js";
import {BAIDU_RUNTIME_POLICY} from "./provider-autonomy.js";
import {CAPABILITY_ABI_VERSION,computeCapabilityManifest} from "./capability-manifest.js";
const API_VERSION="2026-08-16.1";
const SERVICE="compute-worker";
const MAX_BODY_BYTES=65536,MAX_LEASE_SECONDS=7200,DEFAULT_RATE_PER_MIN=30;
const POLICY={fail_closed:true,single_active_task:true,verified_provider_routes_only:true,cloudflare_heavy_compute:false,executor:"kaggle-official",secondary_executor:"google-earth-engine",network:"allowlisted-official-compute-backends",arbitrary_code_upload:false,arbitrary_shell:false,max_retries:0,timeout_cleanup:true,duplicate_task_rejected:true,paid_compute_default:false,paid_fallback:false,baidu_acoin_allowed:false,github_role:"static-source-relay-backup",runtime_authority:"cloudflare"};
const CAPABILITIES={router:true,durable_gate:true,kaggle_official_mcp:true,kaggle_official_api:true,kaggle_current_cpu_t4_e2e_verified:true,cpu:true,gpu_t4:true,google_earth_engine:true,google_earth_engine_role:"gis-geospatial-specialist",google_earth_engine_generic_python:false,copernicus_openeo:true,copernicus_openeo_role:"sentinel-datacube-geospatial",wolfram_alpha:true,wolfram_alpha_role:"symbolic-computational-knowledge",wolfram_alpha_arbitrary_code:false,wolfram_alpha_live_e2e_verified:false,modal_bounded_compute:true,modal_generic_run_route:false,modal_route_eligibility:"live-health-required",baidu_aistudio:true,baidu_aistudio_role:"china-general-compute-on-demand",baidu_aistudio_unattended:false,baidu_aistudio_route_eligible:false,baidu_aistudio_acceptance:"quarantined-paddle2.6-paddle2.5-candidate-paddle2.4",google_colab_unattended:false,bridge_required:false,profiles:["core","bayesian","simulation","causal","finance","gis","gpu","optimization"],heavy_suites:["kaggle_cpu","kaggle_t4","cooperation_chaos_100k","routing_budget_140k"],specialized_suites:["earth_engine_geospatial","copernicus_openeo","wolfram_symbolic_knowledge"]};
const now=()=>new Date().toISOString(),rid=()=>crypto.randomUUID();
const int=(v,d)=>{const n=Number(v);return Number.isFinite(n)?Math.trunc(n):d};
const envTrue=v=>String(v||"").trim().toLowerCase()==="true";
const json=(body,status=200)=>Response.json(body,{status,headers:{"cache-control":"no-store"}});
const error=(code,message,status=400,details)=>json({ok:false,error:code,message,...(details?{details:redact(details)}:{})},status);
function redact(v){if(Array.isArray(v))return v.map(redact);if(v&&typeof v==="object"){const o={};for(const[k,x]of Object.entries(v))o[k]=/token|secret|password|authorization|cookie|api.?key|app.?id|service.?account|private.?key/i.test(k)?"[REDACTED]":redact(x);return o}return v}
async function parseJson(req){const n=Number(req.headers.get("content-length")||0);if(n>MAX_BODY_BYTES)throw Object.assign(new Error("BODY_TOO_LARGE"),{status:413});const t=await req.text();if(new TextEncoder().encode(t).length>MAX_BODY_BYTES)throw Object.assign(new Error("BODY_TOO_LARGE"),{status:413});if(!t)return{};try{return JSON.parse(t)}catch{throw Object.assign(new Error("INVALID_REQUEST"),{status:400})}}
async function sha256Text(t){const h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(t));return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function gate(env,shard="global"){return env.CENTER_GATE.get(env.CENTER_GATE.idFromName(shard))}
async function gateCall(env,path,method="GET",body,shard="global"){const init={method,headers:{"content-type":"application/json"}};if(body!==undefined)init.body=JSON.stringify(body);const r=await gate(env,shard).fetch(new Request(`https://gate.internal${path}`,init));return{http:r.status,...await r.json().catch(()=>({ok:false,error:"GATE_BAD_RESPONSE"}))}}
const loadTask=(env,id)=>gateCall(env,`/task/${encodeURIComponent(id)}`,"GET",undefined,`task:${id}`);
const saveTask=(env,id,p)=>gateCall(env,`/task/${encodeURIComponent(id)}`,"POST",p,`task:${id}`);
const acquire=(env,id,ttl)=>gateCall(env,"/acquire","POST",{task_id:id,kind:"compute",lease_seconds:ttl});
const release=(env,id)=>gateCall(env,"/release","POST",{task_id:id});
export class CenterGate{
  constructor(state){this.state=state}
  async fetch(req){const u=new URL(req.url),s=this.state.storage,j=async()=>{try{return await req.json()}catch{return{}}};const active=async()=>{const a=await s.get("active");if(a&&a.expires_at_ms<=Date.now()){await s.delete("active");return null}return a||null};
    if(req.method==="GET"&&u.pathname==="/state")return json({ok:true,active:await active()});
    if(req.method==="POST"&&u.pathname==="/acquire"){const b=await j(),a=await active();if(a)return json({ok:false,error:"BUSY",active:a},409);const id=String(b.task_id||"");if(!id)return json({ok:false,error:"INVALID_REQUEST"},400);const lease=Math.max(30,Math.min(MAX_LEASE_SECONDS,int(b.lease_seconds,1800))),rec={task_id:id,kind:String(b.kind||"task"),acquired_at:now(),expires_at_ms:Date.now()+lease*1000};await s.put("active",rec);return json({ok:true,active:rec})}
    if(req.method==="POST"&&u.pathname==="/release"){const b=await j(),a=await active();if(!a)return json({ok:true,released:false});if(a.task_id!==b.task_id)return json({ok:false,error:"LOCK_OWNER_MISMATCH",active:a},409);await s.delete("active");return json({ok:true,released:true})}
    if(req.method==="POST"&&u.pathname==="/rate"){const b=await j(),lim=Math.max(1,Math.min(1000,int(b.limit,DEFAULT_RATE_PER_MIN))),m=Math.floor(Date.now()/60000),k=`rate:${m}`,c=(await s.get(k)||0)+1;await s.put(k,c);await s.delete(`rate:${m-2}`);return c<=lim?json({ok:true,count:c,limit:lim}):json({ok:false,error:"RATE_LIMITED",count:c,limit:lim},429)}
    let m=u.pathname.match(/^\/task\/([^/]+)$/);if(m&&req.method==="GET")return json({ok:true,task:await s.get(`task:${decodeURIComponent(m[1])}`)||null});if(m&&req.method==="POST"){const id=decodeURIComponent(m[1]),old=await s.get(`task:${id}`)||{},rec={...old,...redact(await j()),task_id:id};await s.put(`task:${id}`,rec);return json({ok:true,task:rec})}
    m=u.pathname.match(/^\/task\/([^/]+)\/cancel$/);if(m&&req.method==="POST"){const id=decodeURIComponent(m[1]),k=`task:${id}`,old=await s.get(k);if(!old)return json({ok:false,error:"TASK_NOT_FOUND"},404);const rec={...old,cancel_requested:true,cancel_requested_at:now()};await s.put(k,rec);return json({ok:true,task:rec})}
    return json({ok:false,error:"GATE_ROUTE_NOT_FOUND"},404)
  }
}
function readiness(env){const b=baiduAIStudioMeta(),o=openEOMeta(),kaggleConfigured=Boolean(env.KAGGLE_API_TOKEN),googleConfigured=Boolean(env.GOOGLE_EE_SERVICE_ACCOUNT_JSON||env.GOOGLE_CLOUD_CREDENTIALS),openEOConfigured=Boolean(env.CDSE_CLIENT_ID&&env.CDSE_CLIENT_SECRET),wolframConfigured=Boolean(env.WOLFRAM_APP_ID),wolframVerified=envTrue(env.WOLFRAM_LIVE_E2E_VERIFIED);return{primary_provider:"kaggle",kaggle:{official_api:"https://api.kaggle.com/v1",official_mcp:"https://www.kaggle.com/mcp",api_token_configured:kaggleConfigured,bridge_required:false,historically_verified:true,live_health_required:true,route_eligible:kaggleConfigured,route_eligibility:"token-and-live-health-required",acceptance_state:"verified-current-cpu-t4-e2e"},modal:{role:"bounded-general-serverless-cpu-gpu",generic_run_route:false,route_eligible:false,route_eligibility:"live-health-required",acceptance_state:"cpu-t4-e2e-verified"},google_earth_engine:{role:"gis-geospatial-specialist",service_account_configured:googleConfigured,project_override_configured:Boolean(env.GOOGLE_EE_PROJECT_ID||env.GOOGLE_CLOUD_PROJECT),project_can_fallback_to_service_account_json:true,generic_python:false,route_eligible:googleConfigured,route_scope:"specialized-geospatial"},copernicus_openeo:{role:"sentinel-datacube-geospatial",credentials_configured:openEOConfigured,endpoint:o.endpoint||"https://openeo.dataspace.copernicus.eu",route_eligible:openEOConfigured,route_scope:"specialized-geospatial"},wolfram_alpha:{role:"symbolic-computational-knowledge",app_id_configured:wolframConfigured,live_e2e_verified:wolframVerified,endpoint:"https://api.wolframalpha.com/v2/query",route_eligible:wolframConfigured&&wolframVerified,route_scope:"specialized-knowledge",arbitrary_code:false},baidu_aistudio:{role:b.role,access_token_configured:Boolean(env.BAIDU_AISTUDIO_ACCESS_TOKEN),operational_mode:b.operational_mode,payment_mode:BAIDU_RUNTIME_POLICY.payment,acoin_allowed:BAIDU_RUNTIME_POLICY.acoin_allowed,paid_fallback:BAIDU_RUNTIME_POLICY.paid_fallback,daily_maintenance_required:b.daily_maintenance_required,daily_checkin_required:b.daily_checkin_required,unattended_ready:false,production_runtime:BAIDU_RUNTIME_POLICY.production_runtime,candidate_runtime:BAIDU_RUNTIME_POLICY.candidate_runtime,quarantined_runtimes:BAIDU_RUNTIME_POLICY.quarantined_runtimes,automatic_candidate_execution:BAIDU_RUNTIME_POLICY.automatic_candidate_execution,route_eligible:false,acceptance_state:"quarantined-paddle2.6-paddle2.5-candidate-paddle2.4",native_http_candidate:false},google_colab:{unattended_executor:false,role:"interactive-manual-backup-only",route_eligible:false}}}
async function run(req,env){
  const rate=await gateCall(env,"/rate","POST",{limit:int(env.RATE_LIMIT_PER_MIN,DEFAULT_RATE_PER_MIN)});if(!rate.ok)return error("RATE_LIMITED","Compute budget exceeded",429,rate);
  const b=await parseJson(req),id=String(b.task_id||b.request_id||rid()),profile=String(b.profile||"core"),requestedProvider=String(b.provider||b.executor||"kaggle").toLowerCase(),provider=requestedProvider==="wolfram"?"wolfram-alpha":requestedProvider;
  if(!CAPABILITIES.profiles.includes(profile))return error("INVALID_REQUEST","Unknown compute profile",400,{allowed:CAPABILITIES.profiles});
  if(!["kaggle","wolfram-alpha"].includes(provider))return error("INVALID_REQUEST","Unknown compute provider",400,{allowed:["kaggle","wolfram-alpha"]});
  if(provider==="wolfram-alpha"&&!envTrue(env.WOLFRAM_LIVE_E2E_VERIFIED))return error("PROVIDER_NOT_VERIFIED","Wolfram Alpha is registered but live E2E is not verified; fail-closed routing is active",503,{provider,route_eligible:false});
  const previous=await loadTask(env,id);if(previous.task)return error("DUPLICATE_TASK","task_id already exists; duplicate compute execution blocked",409,{task_id:id,status:previous.task.status});
  const timeout=Math.max(60,Math.min(900,int(b.timeout_seconds,300))),lock=await acquire(env,id,timeout);if(!lock.ok)return error("BUSY","Another compute task is active",409,lock.active);
  try{
    await saveTask(env,id,{status:"accepted",profile,gpu:provider==="kaggle"&&Boolean(b.gpu||profile==="gpu"),created_at:now(),executor:provider==="wolfram-alpha"?"wolfram-alpha":"kaggle-official",request_id:b.request_id||null});
    if(provider==="wolfram-alpha"){
      if(!env.WOLFRAM_APP_ID){await saveTask(env,id,{status:"failed",error:"UPSTREAM_AUTH_FAILED",finished_at:now()});await release(env,id);return error("UPSTREAM_AUTH_FAILED","WOLFRAM_APP_ID is not configured",503,{task_id:id})}
      const query=b?.input?.query??b?.input?.input??b?.query,out=await queryWolfram(env,query,{units:b?.input?.units}),digest=await sha256Text(JSON.stringify(out));
      await saveTask(env,id,{status:"completed",executor:"wolfram-alpha",result_digest:digest,finished_at:now()});await release(env,id);
      return json({ok:true,task_id:id,status:"completed",executor:"wolfram-alpha",result:out,result_digest:digest});
    }
    if(!env.KAGGLE_API_TOKEN){await saveTask(env,id,{status:"failed",error:"UPSTREAM_AUTH_FAILED",finished_at:now()});await release(env,id);return error("UPSTREAM_AUTH_FAILED","KAGGLE_API_TOKEN is not configured",503,{task_id:id})}
    const out=await dispatch(env,{task_id:id,profile,input:b.input||{},timeout_seconds:timeout,gpu:Boolean(b.gpu||profile==="gpu")});
    await saveTask(env,id,{status:"running",executor:"kaggle-official",user_name:out.user_name,kernel_slug:out.kernel_slug,ref:out.ref,version_number:out.version_number,gpu:out.gpu,machine_shape:out.machine_shape,started_at:now()});
    return json({ok:true,task_id:id,status:"running",executor:"kaggle-official",machine_shape:out.machine_shape},202);
  }catch(e){await saveTask(env,id,{status:"failed",error:String(e?.message||e),finished_at:now()});await release(env,id);return error(e?.message||"UPSTREAM_UNAVAILABLE",provider==="wolfram-alpha"?"Wolfram Alpha execution failed":"Kaggle official dispatch failed",e?.status||502,{task_id:id,...(e?.details||{})})}
}
async function handle(req,env){const u=new URL(req.url);if(req.method==="GET"&&u.pathname==="/health")return json({ok:true,status:"ready",service:SERVICE,api_version:API_VERSION,compute_backends:readiness(env)});if(req.method==="GET"&&(u.pathname==="/v1/policy"||u.pathname==="/policy"))return json({ok:true,service:SERVICE,policy:POLICY});if(req.method==="GET"&&(u.pathname==="/v1/capabilities"||u.pathname==="/capabilities")){const compute_backends=readiness(env);return json({ok:true,service:SERVICE,capabilities:CAPABILITIES,compute_backends,kaggle:officialMeta(),baidu:baiduAIStudioMeta(),openeo:openEOMeta(),wolfram:wolframMeta(),capability_abi_version:CAPABILITY_ABI_VERSION,capability_manifest:computeCapabilityManifest({backends:compute_backends})})}if(req.method==="GET"&&(u.pathname==="/v1/quota"||u.pathname==="/quota"))return json({ok:true,rate_limit_per_min:int(env.RATE_LIMIT_PER_MIN,DEFAULT_RATE_PER_MIN),single_active_task:true,max_runtime_seconds:900,max_retries:0,paid_fallback:false});if(req.method==="GET"&&u.pathname==="/source")return json({ok:true,service:SERVICE,api_version:API_VERSION,source_digest:await sha256Text(JSON.stringify({SERVICE,API_VERSION,POLICY,CAPABILITIES})),secrets_redacted:true});if(req.method==="GET"&&u.pathname==="/v1/acceptance/latest")return json({ok:true,service:SERVICE,status:"production-verified-with-quarantines",code_gate:"deterministic-predeploy",providers:{google_earth_engine:"verified",kaggle:"verified-current-cpu-t4-e2e-live-health-required",modal:"cpu-t4-e2e-verified-live-health-required-bounded-route",baidu_aistudio:"quarantined-paddle2.6-paddle2.5-candidate-paddle2.4-no-production-runtime",copernicus_openeo:"health-probe",wolfram_alpha:"registered-awaiting-live-e2e"}});if(req.method==="GET"&&u.pathname==="/openapi.json")return json({openapi:"3.1.0",info:{title:"Compute Center",version:API_VERSION},paths:{"/health":{get:{}},"/v1/policy":{get:{}},"/v1/capabilities":{get:{}},"/v1/providers/kaggle/meta":{get:{}},"/v1/providers/kaggle/health":{get:{}},"/v1/providers/modal/meta":{get:{}},"/v1/providers/modal/health":{get:{}},"/v1/providers/modal/compute":{post:{}},"/v1/providers/baidu/meta":{get:{}},"/v1/providers/baidu/health":{get:{}},"/v1/providers/google-ee/meta":{get:{}},"/v1/providers/google-ee/health":{get:{}},"/v1/providers/openeo/meta":{get:{}},"/v1/providers/openeo/health":{get:{}},"/v1/providers/wolfram/meta":{get:{}},"/v1/providers/wolfram/health":{get:{}},"/v1/run":{post:{}},"/v1/status":{post:{}},"/v1/cancel":{post:{}}}});if(req.method==="POST"&&u.pathname==="/v1/run")return run(req,env);return error("INVALID_REQUEST","Route not found",404)}
export default{async fetch(req,env,ctx){try{return await handle(req,env,ctx)}catch(e){return error(e?.message||"INTERNAL_ERROR","Request failed",e?.status||500,e?.details)}}};
