const P=(label,domains,models,notes="")=>Object.freeze({label,domains:Object.freeze(domains),models:Object.freeze(models),notes});
export const INDUSTRY_PACKS=Object.freeze({
  commercial_real_estate:P("商业地产/商圈",["location_intelligence","real_estate_urban","business_management","transport_mobility"],["location_fusion","three_ring_trade_area","huff_trade_area","gravity_od","competitor_diversion","accessibility_score","weighted_index","real_estate_urban.valuation.hedonic_regression","business_management.demand.regression"],"开放位置情报优先；真实LBS校准暂缓"),
  retail_consumer:P("零售/消费",["business_management","marketing_growth","location_intelligence","social_behavior_psychology"],["break_even","eoq","inventory_policy","arc_price_elasticity","hhi","business_management.demand.regression","business_management.customer.churn","business_management.segmentation.kmeans","marketing_growth.diffusion.bass_diffusion","social_behavior_psychology.discrete_choice.binary_logit"]),
  banking_finance:P("银行/金融/投资",["finance_investment","risk_reliability","policy_economics"],["npv","irr","historical_var_es","credit_expected_loss","kelly_fraction","black_scholes","finance_investment.portfolio.mean_variance","finance_investment.portfolio.min_volatility","finance_investment.portfolio.max_sharpe","finance_investment.portfolio.cvar","finance_investment.volatility.garch","finance_investment.time_series.arima"]),
  insurance:P("保险/精算",["risk_reliability","finance_investment","business_management"],["credit_expected_loss","weibull_reliability_point","historical_var_es","risk_reliability.reliability.survival","risk_reliability.extreme.gev","risk_reliability.stochastic.monte_carlo"]),
  manufacturing:P("制造/质量/设备",["operations_supply_chain","risk_reliability","business_management"],["pert_schedule","mm1_queue","inventory_policy","eoq","weibull_reliability_point","fault_tree_independent","operations_supply_chain.linear_optimization.milp","operations_supply_chain.scheduling.job_shop","risk_reliability.stochastic.monte_carlo"]),
  logistics_supply_chain:P("物流/供应链",["operations_supply_chain","transport_mobility","risk_reliability"],["inventory_policy","eoq","pert_schedule","operations_supply_chain.routing.vrp","operations_supply_chain.flow.min_cost_flow","operations_supply_chain.facility.facility_location","transport_mobility.network.shortest_path","risk_reliability.stochastic.monte_carlo"]),
  energy_utilities:P("能源/公用事业",["energy_environment","operations_supply_chain","risk_reliability","policy_economics"],["energy_environment.load_forecast.arima","energy_environment.dispatch.economic_dispatch","risk_reliability.extreme.gev","risk_reliability.stochastic.monte_carlo","policy_economics.policy_scenario.sobol"]),
  agriculture_food:P("农业/食品",["business_management","energy_environment","operations_supply_chain","risk_reliability","location_intelligence"],["business_management.demand.regression","inventory_policy","eoq","risk_reliability.extreme.gev","risk_reliability.stochastic.monte_carlo","weighted_index"]),
  tourism_hospitality:P("旅游/酒店",["business_management","marketing_growth","location_intelligence","transport_mobility"],["location_fusion","business_management.demand.arima","business_management.pricing.price_optimization","marketing_growth.diffusion.bass_diffusion","accessibility_score","huff_trade_area"]),
  healthcare_public_health:P("医疗/公共健康",["public_health","operations_supply_chain","risk_reliability"],["sir_local","mm1_queue","public_health.epidemic.seir","public_health.survival.cox","public_health.health_economics.markov_chain","risk_reliability.stochastic.monte_carlo"]),
  public_policy:P("政策/公共治理",["policy_economics","intelligence_analysis","social_behavior_psychology","risk_reliability"],["weighted_decision","bayesian_evidence_fusion","policy_economics.causal_policy.difference_in_differences","policy_economics.causal_policy.synthetic_control","policy_economics.macro.var","policy_economics.input_output.leontief","social_behavior_psychology.agent_based.agent_based_simulation"]),
  intelligence:P("情报/态势研判",["intelligence_analysis","risk_reliability","social_behavior_psychology","policy_economics"],["bayesian_evidence_fusion","weighted_decision","entropy","pagerank","threshold_diffusion","intelligence_analysis.anomaly.isolation_forest","intelligence_analysis.causal_root_cause.effect_estimation","intelligence_analysis.bayesian_network.belief_update","risk_reliability.stochastic.monte_carlo"]),
  social_research:P("社会行为/群体心理",["social_behavior_psychology","policy_economics","intelligence_analysis"],["prospect_value","threshold_diffusion","pagerank","social_behavior_psychology.opinion.deffuant","social_behavior_psychology.opinion.voter_model","social_behavior_psychology.discrete_choice.multinomial_logit","social_behavior_psychology.survey_latent.factor_analysis","policy_economics.causal_policy.difference_in_differences"]),
  media_platform:P("媒体/平台/注意力",["marketing_growth","social_behavior_psychology","intelligence_analysis"],["threshold_diffusion","pagerank","marketing_growth.attribution.markov_attribution","marketing_growth.diffusion.bass_diffusion","intelligence_analysis.anomaly.change_point","social_behavior_psychology.contagion.independent_cascade"]),
  legal_regulatory:P("法律/监管/合规",["intelligence_analysis","policy_economics","risk_reliability"],["bayesian_evidence_fusion","weighted_decision","pagerank","policy_economics.causal_policy.difference_in_differences","intelligence_analysis.anomaly.isolation_forest","fault_tree_independent"]),
  project_management:P("项目管理/工程",["operations_supply_chain","risk_reliability"],["pert_schedule","operations_supply_chain.scheduling.resource_allocation","operations_supply_chain.linear_optimization.milp","risk_reliability.stochastic.monte_carlo","fault_tree_independent"]),
  labor_demography:P("人口/就业/劳动力",["policy_economics","social_behavior_psychology","business_management","location_intelligence"],["policy_economics.econometrics.ols","policy_economics.causal_policy.difference_in_differences","social_behavior_psychology.discrete_choice.binary_logit","business_management.demand.regression","location_fusion"]),
  cyber_resilience_defensive:P("网络与系统韧性（防御）",["risk_reliability","intelligence_analysis","operations_supply_chain"],["fault_tree_independent","pagerank","intelligence_analysis.anomaly.isolation_forest","risk_reliability.reliability.weibull","risk_reliability.stochastic.monte_carlo"],"仅用于防御性可靠性、异常与韧性评估，不包含攻击执行能力")
});

export const STANDARD_WORKFLOWS=Object.freeze({
  open_location_intelligence:{label:"开放位置情报融合",steps:["H3/空间网格预处理","WorldPop/GHSL人口与建成环境","Overture/Foursquare POI","NASA夜间活力","Dynamic World/LCFM土地利用","道路可达性","location_fusion","huff_trade_area","gravity_od","competitor_diversion"],calibration:"deferred-until-benchmark-library",observed_lbs:false},
  business_decision:{label:"商业决策",steps:["需求预测","单位经济","价格弹性","情景模拟","风险","优化","敏感性"]},
  financial_risk:{label:"金融风险",steps:["时间序列","波动率","VaR/ES","压力情景","资产配置","尾部风险"]},
  intelligence_fusion:{label:"情报研判",steps:["证据融合","竞争性假设","关系网络","异常/变点","因果根因","情景树","不确定性"]},
  social_behavior:{label:"社会行为",steps:["离散选择","前景理论","传播扩散","观点动力学","Agent仿真","因果识别"]},
  operations_optimization:{label:"运营优化",steps:["需求/容量","排队","库存","选址","路由","排程","蒙特卡洛压力"]}
});

export function industrySummary(){return{industry_pack_count:Object.keys(INDUSTRY_PACKS).length,workflow_count:Object.keys(STANDARD_WORKFLOWS).length,packs:Object.entries(INDUSTRY_PACKS).map(([id,p])=>({id,label:p.label,domains:p.domains.length,models:p.models.length})),calibration_state:"deferred-until-benchmark-library"}}
export function industryPack(id){const p=INDUSTRY_PACKS[id];return p?{id,...p}:null}
