const MCP_URL="https://www.kaggle.com/mcp";
const MAX_BYTES=2_000_000;
function auth(env){const t=String(env.KAGGLE_API_TOKEN||"").trim();if(!t)throw Object.assign(new Error("KAGGLE_API_TOKEN_NOT_CONFIGURED"),{status:503});return t}
function parsePayload(text){if(!text)return null;try{return JSON.parse(text)}catch{}const events=text.split(/\r?\n\r?\n/);for(const event of events){for(const line of event.split(/\r?\n/)){if(line.startsWith("data:")){const s=line.slice(5).trim();if(!s||s==="[DONE]")continue;try{return JSON.parse(s)}catch{}}}}throw Object.assign(new Error("KAGGLE_MCP_BAD_RESPONSE"),{status:502})}
async function post(env,body,sessionId=null,timeoutMs=15_000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeoutMs);try{const headers={authorization:`Bearer ${auth(env)}`,"content-type":"application/json",accept:"application/json, text/event-stream"};if(sessionId)headers["mcp-session-id"]=sessionId;const r=await fetch(MCP_URL,{method:"POST",headers,body:JSON.stringify(body),signal:c.signal});const text=await r.text();if(new TextEncoder().encode(text).length>MAX_BYTES)throw Object.assign(new Error("KAGGLE_MCP_RESPONSE_TOO_LARGE"),{status:502});if(!r.ok)throw Object.assign(new Error(`KAGGLE_MCP_HTTP_${r.status}`),{status:r.status});return{payload:parsePayload(text),session_id:r.headers.get("mcp-session-id")||sessionId}}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("KAGGLE_MCP_TIMEOUT"),{status:504});throw e}finally{clearTimeout(timer)}}
async function openSession(env){const init=await post(env,{jsonrpc:"2.0",id:`init-${crypto.randomUUID()}`,method:"initialize",params:{protocolVersion:"2025-06-18",capabilities:{},clientInfo:{name:"three-center-compute",version:"2026-08-15"}}});if(init.payload?.error)throw Object.assign(new Error(String(init.payload.error?.message||"KAGGLE_MCP_INIT_FAILED")),{status:502});const sid=init.session_id;try{await post(env,{jsonrpc:"2.0",method:"notifications/initialized",params:{}},sid,8_000)}catch(e){if(![202,204].includes(e?.status))throw e}return sid}
export async function listTools(env){const sid=await openSession(env),r=await post(env,{jsonrpc:"2.0",id:`tools-${crypto.randomUUID()}`,method:"tools/list",params:{}},sid,15_000);if(r.payload?.error)throw Object.assign(new Error(String(r.payload.error?.message||"KAGGLE_MCP_TOOLS_FAILED")),{status:502});return Array.isArray(r.payload?.result?.tools)?r.payload.result.tools:[]}
function cancelScore(t){const x=`${t?.name||""} ${t?.description||""}`.toLowerCase();let s=0;if(x.includes("cancel"))s+=8;if(x.includes("kernel"))s+=5;if(x.includes("notebook"))s+=5;if(x.includes("session"))s+=2;if(x.includes("competition"))s-=10;return s}
function argsFor(tool,task){const props=tool?.inputSchema?.properties||{},required=new Set(tool?.inputSchema?.required||[]),args={},ref=`${task.user_name}/${task.kernel_slug}`,keys=Object.keys(props);for(const k of keys){const n=k.toLowerCase().replace(/[^a-z0-9]/g,"");if(n==="username"||n==="owner"||n==="ownerslug")args[k]=task.user_name;else if(n==="kernelslug"||n==="notebookslug")args[k]=task.kernel_slug;else if(n==="kernel"||n==="notebook"||n==="ref"||n==="slug")args[k]=ref}
  for(const k of required){if(args[k]===undefined)throw Object.assign(new Error(`KAGGLE_MCP_UNSUPPORTED_REQUIRED_ARG_${k}`),{status:502})}return args}
export async function cancelKernel(env,task){const sid=await openSession(env),listed=await post(env,{jsonrpc:"2.0",id:`tools-${crypto.randomUUID()}`,method:"tools/list",params:{}},sid,15_000),tools=Array.isArray(listed.payload?.result?.tools)?listed.payload.result.tools:[],tool=[...tools].sort((a,b)=>cancelScore(b)-cancelScore(a))[0];if(!tool||cancelScore(tool)<8)throw Object.assign(new Error("KAGGLE_MCP_CANCEL_TOOL_NOT_FOUND"),{status:502});const args=argsFor(tool,task),r=await post(env,{jsonrpc:"2.0",id:`cancel-${crypto.randomUUID()}`,method:"tools/call",params:{name:tool.name,arguments:args}},sid,20_000);if(r.payload?.error||r.payload?.result?.isError)throw Object.assign(new Error(String(r.payload?.error?.message||"KAGGLE_MCP_CANCEL_FAILED")),{status:502});return{ok:true,tool:String(tool.name),arguments_shape:Object.keys(args).sort()}}
export async function probeMcp(env){const tools=await listTools(env),names=tools.map(t=>String(t.name||""));return{ok:true,endpoint:MCP_URL,tools_count:names.length,notebook_tools:names.filter(n=>/kernel|notebook/i.test(n)).length,cancel_tool_present:tools.some(t=>cancelScore(t)>=8)}}