const MCP_URL="https://www.kaggle.com/mcp";
const MAX_BYTES=2_000_000;
function auth(env){const t=String(env.KAGGLE_API_TOKEN||"").trim();if(!t)throw Object.assign(new Error("KAGGLE_API_TOKEN_NOT_CONFIGURED"),{status:503});return t}
function parsePayload(text){if(!text)return null;try{return JSON.parse(text)}catch{}const events=text.split(/\r?\n\r?\n/);for(const event of events){for(const line of event.split(/\r?\n/)){if(line.startsWith("data:")){const s=line.slice(5).trim();if(!s||s==="[DONE]")continue;try{return JSON.parse(s)}catch{}}}}throw Object.assign(new Error("KAGGLE_MCP_BAD_RESPONSE"),{status:502})}
async function post(env,body,sessionId=null,timeoutMs=15_000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeoutMs);try{const headers={authorization:`Bearer ${auth(env)}`,"content-type":"application/json",accept:"application/json, text/event-stream"};if(sessionId)headers["mcp-session-id"]=sessionId;const r=await fetch(MCP_URL,{method:"POST",headers,body:JSON.stringify(body),signal:c.signal});const text=await r.text();if(new TextEncoder().encode(text).length>MAX_BYTES)throw Object.assign(new Error("KAGGLE_MCP_RESPONSE_TOO_LARGE"),{status:502});if(!r.ok)throw Object.assign(new Error(`KAGGLE_MCP_HTTP_${r.status}`),{status:r.status});return{payload:parsePayload(text),session_id:r.headers.get("mcp-session-id")||sessionId}}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("KAGGLE_MCP_TIMEOUT"),{status:504});throw e}finally{clearTimeout(timer)}}
async function openSession(env){const init=await post(env,{jsonrpc:"2.0",id:`init-${crypto.randomUUID()}`,method:"initialize",params:{protocolVersion:"2025-06-18",capabilities:{},clientInfo:{name:"three-center-compute",version:"2026-08-15"}}});if(init.payload?.error)throw Object.assign(new Error(String(init.payload.error?.message||"KAGGLE_MCP_INIT_FAILED")),{status:502});const sid=init.session_id;try{await post(env,{jsonrpc:"2.0",method:"notifications/initialized",params:{}},sid,8_000)}catch(e){if(![202,204].includes(e?.status))throw e}return sid}
export async function listTools(env){const sid=await openSession(env),r=await post(env,{jsonrpc:"2.0",id:`tools-${crypto.randomUUID()}`,method:"tools/list",params:{}},sid,15_000);if(r.payload?.error)throw Object.assign(new Error(String(r.payload.error?.message||"KAGGLE_MCP_TOOLS_FAILED")),{status:502});return Array.isArray(r.payload?.result?.tools)?r.payload.result.tools:[]}
const norm=x=>String(x||"").toLowerCase().replace(/[^a-z0-9]/g,"");
function schemaProps(t){return t?.inputSchema?.properties||{}}
function findTool(tools,kind){const scored=tools.map(t=>{const x=`${t?.name||""} ${t?.description||""}`.toLowerCase();let s=0;if(/kernel|notebook/.test(x))s+=4;if(kind==="push"&&/push|save|create/.test(x))s+=8;if(kind==="cancel"&&/cancel/.test(x))s+=8;if(kind==="session"&&/session/.test(x)&&/create|start|run/.test(x))s+=8;if(/competition/.test(x))s-=12;if(kind==="push"&&String(t?.name||"").toLowerCase()==="kernel_push")s+=20;if(kind==="cancel"&&String(t?.name||"").toLowerCase()==="kernel_session_cancel")s+=20;if(kind==="session"&&String(t?.name||"").toLowerCase()==="kernel_session_create")s+=20;return{t,s}}).sort((a,b)=>b.s-a.s);return scored[0]?.s>=8?scored[0].t:null}
function refArgs(tool,task){const props=schemaProps(tool),required=new Set(tool?.inputSchema?.required||[]),args={},ref=`${task.user_name}/${task.kernel_slug}`;for(const k of Object.keys(props)){const n=norm(k);if(n==="username"||n==="owner"||n==="ownerslug")args[k]=task.user_name;else if(n==="kernelslug"||n==="notebookslug")args[k]=task.kernel_slug;else if(n==="kernel"||n==="notebook"||n==="ref"||n==="slug")args[k]=ref}for(const k of required){if(args[k]===undefined)throw Object.assign(new Error(`KAGGLE_MCP_UNSUPPORTED_REQUIRED_ARG_${k}`),{status:502})}return args}
function pushArgs(tool,{title,text,gpu}){const props=schemaProps(tool),required=new Set(tool?.inputSchema?.required||[]),args={};for(const[k,p]of Object.entries(props)){const n=norm(k);if(n==="title"||n==="name")args[k]=title;else if(n==="text"||n==="source"||n==="code")args[k]=text;else if(n==="language")args[k]="python";else if(n==="kerneltype"||n==="notebooktype"||n==="type")args[k]="script";else if(n==="isprivate"||n==="private")args[k]=true;else if(n==="enablegpu"||n==="gpu")args[k]=Boolean(gpu);else if(n==="enabletpu"||n==="tpu")args[k]=false;else if(n==="enableinternet"||n==="internet")args[k]=false;else if(n==="machineshape"||n==="accelerator"){const en=Array.isArray(p?.enum)?p.enum.map(String):[];args[k]=gpu?(en.find(v=>/NvidiaTeslaT4/i.test(v))||en.find(v=>/^T4$/i.test(v))||"NvidiaTeslaT4"):(en.find(v=>/cpu/i.test(v))||"cpu")}}for(const k of required){if(args[k]===undefined)throw Object.assign(new Error(`KAGGLE_MCP_UNSUPPORTED_REQUIRED_ARG_${k}`),{status:502})}return args}
async function callTool(env,tool,args,timeoutMs=25_000){const sid=await openSession(env),r=await post(env,{jsonrpc:"2.0",id:`call-${crypto.randomUUID()}`,method:"tools/call",params:{name:tool.name,arguments:args}},sid,timeoutMs);if(r.payload?.error||r.payload?.result?.isError)throw Object.assign(new Error(String(r.payload?.error?.message||"KAGGLE_MCP_TOOL_FAILED")),{status:502});return r.payload?.result||{}}
export async function pushKernel(env,{title,text,gpu=false}){const tools=await listTools(env),tool=findTool(tools,"push");if(!tool)throw Object.assign(new Error("KAGGLE_MCP_PUSH_TOOL_NOT_FOUND"),{status:502});const args=pushArgs(tool,{title,text,gpu}),result=await callTool(env,tool,args,30_000);return{ok:true,tool:String(tool.name),arguments_shape:Object.keys(args).sort(),gpu_argument_sent:Object.entries(args).some(([k,v])=>/(gpu|machineshape|accelerator)/i.test(k)&&Boolean(v)),result_is_error:Boolean(result?.isError)}}
export async function createKernelSession(env,task,{gpu=false}={}){const tools=await listTools(env),tool=findTool(tools,"session");if(!tool)throw Object.assign(new Error("KAGGLE_MCP_SESSION_CREATE_TOOL_NOT_FOUND"),{status:502});const args=refArgs(tool,task),props=schemaProps(tool);for(const[k,p]of Object.entries(props)){const n=norm(k);if(n==="machineshape"||n==="accelerator"){const en=Array.isArray(p?.enum)?p.enum.map(String):[];args[k]=gpu?(en.find(v=>/NvidiaTeslaT4/i.test(v))||en.find(v=>/^T4$/i.test(v))||"NvidiaTeslaT4"):(en.find(v=>/cpu/i.test(v))||"cpu");}else if(n==="enablegpu"||n==="gpu")args[k]=Boolean(gpu)}const result=await callTool(env,tool,args,25_000);return{ok:true,tool:String(tool.name),arguments_shape:Object.keys(args).sort(),result_is_error:Boolean(result?.isError)}}
export async function cancelKernel(env,task){const tools=await listTools(env),tool=findTool(tools,"cancel");if(!tool)throw Object.assign(new Error("KAGGLE_MCP_CANCEL_TOOL_NOT_FOUND"),{status:502});const args=refArgs(tool,task),result=await callTool(env,tool,args,20_000);return{ok:true,tool:String(tool.name),arguments_shape:Object.keys(args).sort(),result_is_error:Boolean(result?.isError)}}
export async function probeMcp(env){const tools=await listTools(env),push=findTool(tools,"push"),session=findTool(tools,"session"),cancel=findTool(tools,"cancel"),pushProps=push?Object.keys(schemaProps(push)):[],sessionProps=session?Object.keys(schemaProps(session)):[];return{ok:true,endpoint:MCP_URL,tools_count:tools.length,notebook_tools:tools.filter(t=>/kernel|notebook/i.test(`${t?.name||""} ${t?.description||""}`)).length,push_tool_present:Boolean(push),push_accepts_gpu:pushProps.some(k=>/(gpu|machine.?shape|accelerator)/i.test(k)),session_create_present:Boolean(session),session_accepts_gpu:sessionProps.some(k=>/(gpu|machine.?shape|accelerator)/i.test(k)),cancel_tool_present:Boolean(cancel)}}