const MAX_ITEMS=500,MAX_MATRIX=120,EPS=1e-12;
const err=(m,status=400,details)=>{throw Object.assign(new Error(m),{status,details})};
const num=(v,name,{min=-Infinity,max=Infinity,def}={})=>{const n=Number(v);if(!Number.isFinite(n)){if(def!==undefined)return def;err(`INVALID_${name.toUpperCase()}`)}if(n<min||n>max)err(`INVALID_${name.toUpperCase()}`,400,{min,max});return n};
const arr=(v,name,max=MAX_ITEMS)=>{if(!Array.isArray(v)||v.length===0||v.length>max)err(`INVALID_${name.toUpperCase()}`,400,{max});return v};
const id=(v,i)=>String(v??i).slice(0,96);
const clean=(n)=>Number.isFinite(n)?Number(n.toFixed(12)):null;
const sum=a=>a.reduce((s,x)=>s+x,0);
const mean=a=>sum(a)/Math.max(1,a.length);
function normalizeWeights(weights){const w=arr(weights,"weights").map((x,i)=>num(typeof x==="object"?x.weight:x,`weight_${i}`,{min:0,max:1e9})),s=sum(w);if(s<=EPS)err("ZERO_WEIGHT_SUM");return w.map(x=>x/s)}

function threeRing(args){
  const items=arr(args.items,"items").map((x,i)=>({id:id(x.id,i),travel_time:num(x.travel_time??x.minutes,`travel_time_${i}`,{min:0,max:1440}),demand:num(x.demand??x.population??1,`demand_${i}`,{min:0,max:1e12}),attraction:num(x.attraction??1,`attraction_${i}`,{min:0,max:1e12})}));
  const t1=num(args.core_minutes,"core_minutes",{min:1,max:240,def:10}),t2=num(args.secondary_minutes,"secondary_minutes",{min:t1,max:480,def:Math.max(20,t1)}),t3=num(args.fringe_minutes,"fringe_minutes",{min:t2,max:720,def:Math.max(30,t2)});
  const rings={core:[],secondary:[],fringe:[],outside:[]};
  for(const x of items){const r=x.travel_time<=t1?"core":x.travel_time<=t2?"secondary":x.travel_time<=t3?"fringe":"outside";rings[r].push(x)}
  const metrics={};for(const[k,v]of Object.entries(rings))metrics[k]={cells:v.length,demand:clean(sum(v.map(x=>x.demand))),weighted_attraction:clean(sum(v.map(x=>x.demand*x.attraction)))};
  return{model:"three_ring_trade_area",thresholds_minutes:[t1,t2,t3],rings,metrics};
}
function huff(args){
  const origins=arr(args.origins,"origins",200),alpha=num(args.alpha,"alpha",{min:0.01,max:10,def:1}),beta=num(args.beta,"beta",{min:0.01,max:10,def:2});
  const rows=origins.map((o,oi)=>{const demand=num(o.demand??o.population??1,`demand_${oi}`,{min:0,max:1e12}),choices=arr(o.destinations,`destinations_${oi}`,80).map((d,di)=>{const a=num(d.attraction??d.size??1,`attraction_${oi}_${di}`,{min:0,max:1e12}),c=num(d.cost??d.travel_time??d.distance,`cost_${oi}_${di}`,{min:0.001,max:1e9});return{id:id(d.id,di),score:Math.pow(Math.max(a,EPS),alpha)/Math.pow(c,beta)}});const den=sum(choices.map(x=>x.score));if(den<=EPS)err("HUFF_ZERO_DENOMINATOR");return{id:id(o.id,oi),demand,probabilities:choices.map(x=>({id:x.id,probability:clean(x.score/den),expected_flow:clean(demand*x.score/den)}))}});
  const totals={};for(const r of rows)for(const p of r.probabilities)totals[p.id]=(totals[p.id]||0)+p.expected_flow;
  return{model:"huff_trade_area",alpha,beta,origins:rows,destination_expected_flow:Object.fromEntries(Object.entries(totals).map(([k,v])=>[k,clean(v)]))};
}
function gravity(args){
  const origins=arr(args.origins,"origins",MAX_MATRIX),destinations=arr(args.destinations,"destinations",MAX_MATRIX);if(origins.length*destinations.length>5000)err("MATRIX_TOO_LARGE",413,{max_cells:5000});
  const beta=num(args.beta,"beta",{min:0.000001,max:50,def:0.1}),power=num(args.destination_power,"destination_power",{min:0,max:5,def:1}),costs=arr(args.cost_matrix,"cost_matrix",MAX_MATRIX);if(costs.length!==origins.length)err("COST_MATRIX_SHAPE_MISMATCH");
  const dest=destinations.map((d,j)=>({id:id(d.id,j),mass:num(d.mass??d.attraction??1,`destination_mass_${j}`,{min:0,max:1e12})}));
  const rows=[];const destTotals=Object.fromEntries(dest.map(x=>[x.id,0]));
  for(let i=0;i<origins.length;i++){const o=origins[i],mass=num(o.mass??o.population??o.demand??1,`origin_mass_${i}`,{min:0,max:1e12}),row=costs[i];if(!Array.isArray(row)||row.length!==dest.length)err("COST_MATRIX_SHAPE_MISMATCH");const scores=dest.map((d,j)=>{const c=num(row[j],`cost_${i}_${j}`,{min:0,max:1e9});return Math.pow(Math.max(d.mass,EPS),power)*Math.exp(-beta*c)}),den=sum(scores);if(den<=EPS)err("GRAVITY_ZERO_DENOMINATOR");const flows=dest.map((d,j)=>{const f=mass*scores[j]/den;destTotals[d.id]+=f;return{id:d.id,cost:row[j],flow:clean(f)}});rows.push({id:id(o.id,i),mass,flows})}
  return{model:"gravity_od",beta,destination_power:power,origins:rows,destination_flow:Object.fromEntries(Object.entries(destTotals).map(([k,v])=>[k,clean(v)]))};
}
function diversion(args){
  const base=huff(args),target=String(args.target_id||"");if(!target)err("ARG_REQUIRED:target_id");
  const diversion={};let targetFlow=0;
  for(const r of base.origins){const tp=r.probabilities.find(x=>x.id===target);if(!tp)continue;targetFlow+=tp.expected_flow;const others=r.probabilities.filter(x=>x.id!==target),den=sum(others.map(x=>x.probability));if(den<=EPS)continue;for(const p of others)diversion[p.id]=(diversion[p.id]||0)+tp.expected_flow*(p.probability/den)}
  return{model:"competitor_diversion",target_id:target,target_expected_flow:clean(targetFlow),diverted_to:Object.fromEntries(Object.entries(diversion).map(([k,v])=>[k,clean(v)])),baseline:base.destination_expected_flow};
}
function accessibility(args){
  const opportunities=arr(args.opportunities,"opportunities"),beta=num(args.beta,"beta",{min:0.000001,max:50,def:0.1}),power=num(args.power,"power",{min:0.01,max:10,def:1});let score=0;const parts=[];
  for(let i=0;i<opportunities.length;i++){const x=opportunities[i],value=num(x.value??x.opportunities??1,`value_${i}`,{min:0,max:1e12}),cost=num(x.cost??x.travel_time??x.distance,`cost_${i}`,{min:0,max:1e9}),component=Math.pow(value,power)*Math.exp(-beta*cost);score+=component;parts.push({id:id(x.id,i),component:clean(component)})}
  return{model:"accessibility_score",beta,power,score:clean(score),components:parts};
}
function weightedIndex(args){
  const features=arr(args.features,"features"),weights=normalizeWeights(features.map(x=>x.weight??1));let score=0;const components=features.map((x,i)=>{const value=num(x.value,`value_${i}`,{min:-1e12,max:1e12}),min=num(x.min,`min_${i}`,{def:0}),max=num(x.max,`max_${i}`,{def:1});if(max<=min)err("INVALID_FEATURE_RANGE",400,{index:i});let z=(value-min)/(max-min);z=Math.max(0,Math.min(1,z));if(x.direction==="negative")z=1-z;const c=z*weights[i];score+=c;return{id:id(x.id,i),normalized:clean(z),weight:clean(weights[i]),contribution:clean(c)}});return{model:"weighted_index",score_0_100:clean(score*100),components};
}
function bayesEvidence(args){
  let prior=num(args.prior_probability,"prior_probability",{min:0.000001,max:0.999999,def:0.5}),odds=prior/(1-prior);const evidence=arr(args.evidence,"evidence").map((e,i)=>{let lr;if(e.likelihood_ratio!==undefined)lr=num(e.likelihood_ratio,`likelihood_ratio_${i}`,{min:0.000001,max:1e9});else{const ph=num(e.p_if_h,`p_if_h_${i}`,{min:0.000001,max:0.999999}),pn=num(e.p_if_not_h,`p_if_not_h_${i}`,{min:0.000001,max:0.999999});lr=ph/pn}odds*=lr;return{id:id(e.id,i),likelihood_ratio:clean(lr)}});const posterior=odds/(1+odds);return{model:"bayesian_evidence_fusion",prior_probability:prior,posterior_probability:clean(posterior),posterior_odds:clean(odds),evidence};
}
function weightedDecision(args){
  const criteria=arr(args.criteria,"criteria",100),weights=normalizeWeights(criteria.map(c=>c.weight??1)),options=arr(args.options,"options",100);const scored=options.map((o,oi)=>{const values=arr(o.values,`values_${oi}`,100);if(values.length!==criteria.length)err("DECISION_MATRIX_SHAPE_MISMATCH");let score=0;const parts=values.map((v,i)=>{const n=num(v,`value_${oi}_${i}`,{min:0,max:1}),c=n*weights[i];score+=c;return{criterion:id(criteria[i].id,i),value:n,contribution:clean(c)}});return{id:id(o.id,oi),score:clean(score),components:parts}}).sort((a,b)=>b.score-a.score);return{model:"weighted_decision",ranking:scored};
}
function expectedValue(args){const scenarios=arr(args.scenarios,"scenarios",200);let pSum=0,ev=0;const out=scenarios.map((s,i)=>{const p=num(s.probability,`probability_${i}`,{min:0,max:1}),v=num(s.value??s.payoff,`value_${i}`,{min:-1e15,max:1e15});pSum+=p;ev+=p*v;return{id:id(s.id,i),probability:p,value:v,contribution:clean(p*v)}});if(Math.abs(pSum-1)>1e-6)err("PROBABILITIES_MUST_SUM_TO_ONE",400,{sum:pSum});return{model:"expected_value",expected_value:clean(ev),scenarios:out};}
function entropy(args){const probs=arr(args.probabilities,"probabilities",MAX_ITEMS).map((p,i)=>num(p,`probability_${i}`,{min:0,max:1})),s=sum(probs);if(Math.abs(s-1)>1e-6)err("PROBABILITIES_MUST_SUM_TO_ONE",400,{sum:s});let h=0;for(const p of probs)if(p>0)h-=p*Math.log2(p);return{model:"entropy",bits:clean(h),normalized:clean(h/Math.log2(probs.length))};}
function markov(args){const matrix=arr(args.transition_matrix,"transition_matrix",MAX_MATRIX),n=matrix.length;if(n>MAX_MATRIX)err("MATRIX_TOO_LARGE");for(let i=0;i<n;i++){if(!Array.isArray(matrix[i])||matrix[i].length!==n)err("TRANSITION_MATRIX_SHAPE_MISMATCH");const r=matrix[i].map((x,j)=>num(x,`transition_${i}_${j}`,{min:0,max:1}));if(Math.abs(sum(r)-1)>1e-6)err("TRANSITION_ROW_MUST_SUM_TO_ONE",400,{row:i});matrix[i]=r}let state=arr(args.initial_state,"initial_state",MAX_MATRIX).map((x,i)=>num(x,`initial_${i}`,{min:0,max:1}));if(state.length!==n||Math.abs(sum(state)-1)>1e-6)err("INITIAL_STATE_INVALID");const steps=Math.trunc(num(args.steps,"steps",{min:1,max:1000,def:1}));for(let k=0;k<steps;k++){const next=Array(n).fill(0);for(let i=0;i<n;i++)for(let j=0;j<n;j++)next[j]+=state[i]*matrix[i][j];state=next}return{model:"markov_chain",steps,state:state.map(clean)};}
function pageRank(args){const nodes=arr(args.nodes,"nodes",200).map((x,i)=>id(typeof x==="object"?x.id:x,i)),index=new Map(nodes.map((x,i)=>[x,i])),n=nodes.length,edges=arr(args.edges,"edges",1000),d=num(args.damping,"damping",{min:0.1,max:0.99,def:0.85}),iters=Math.trunc(num(args.iterations,"iterations",{min:1,max:200,def:50}));const out=Array(n).fill(0).map(()=>[]);for(const e of edges){const a=index.get(String(e.source)),b=index.get(String(e.target));if(a===undefined||b===undefined)err("EDGE_NODE_NOT_FOUND");out[a].push(b)}let r=Array(n).fill(1/n);for(let k=0;k<iters;k++){const next=Array(n).fill((1-d)/n);let dangling=0;for(let i=0;i<n;i++){if(!out[i].length){dangling+=r[i];continue}const share=d*r[i]/out[i].length;for(const j of out[i])next[j]+=share}const add=d*dangling/n;for(let i=0;i<n;i++)next[i]+=add;r=next}return{model:"pagerank",scores:nodes.map((x,i)=>({id:x,score:clean(r[i])})).sort((a,b)=>b.score-a.score)};}
function thresholdDiffusion(args){const nodes=arr(args.nodes,"nodes",300).map((x,i)=>({id:id(typeof x==="object"?x.id:x,i),threshold:num(typeof x==="object"?x.threshold:args.threshold,`threshold_${i}`,{min:0,max:1,def:0.5})})),idx=new Map(nodes.map((x,i)=>[x.id,i])),edges=arr(args.edges,"edges",1500),adj=Array(nodes.length).fill(0).map(()=>[]);for(const e of edges){const a=idx.get(String(e.source)),b=idx.get(String(e.target));if(a===undefined||b===undefined)err("EDGE_NODE_NOT_FOUND");adj[a].push(b);if(e.directed!==true)adj[b].push(a)}const active=new Set(arr(args.seeds,"seeds",300).map(String));for(const s of active)if(!idx.has(s))err("SEED_NODE_NOT_FOUND");const maxSteps=Math.trunc(num(args.max_steps,"max_steps",{min:1,max:100,def:20}));const history=[active.size];for(let step=0;step<maxSteps;step++){const add=[];for(let i=0;i<nodes.length;i++){const node=nodes[i];if(active.has(node.id)||adj[i].length===0)continue;const frac=adj[i].filter(j=>active.has(nodes[j].id)).length/adj[i].length;if(frac>=node.threshold)add.push(node.id)}if(!add.length)break;for(const x of add)active.add(x);history.push(active.size)}return{model:"threshold_diffusion",active_count:active.size,active:[...active],history};}
function prospect(args){const x=num(args.outcome,"outcome",{min:-1e15,max:1e15}),reference=num(args.reference,"reference",{min:-1e15,max:1e15,def:0}),alpha=num(args.alpha,"alpha",{min:0.01,max:2,def:0.88}),beta=num(args.beta,"beta",{min:0.01,max:2,def:0.88}),lambda=num(args.loss_aversion,"loss_aversion",{min:0,max:20,def:2.25}),d=x-reference,value=d>=0?Math.pow(d,alpha):-lambda*Math.pow(-d,beta);return{model:"prospect_value",outcome:x,reference,value:clean(value)};}
function mm1(args){const lambda=num(args.arrival_rate,"arrival_rate",{min:0,max:1e12}),mu=num(args.service_rate,"service_rate",{min:EPS,max:1e12});if(lambda>=mu)err("QUEUE_UNSTABLE",400,{requirement:"arrival_rate < service_rate"});const rho=lambda/mu,L=rho/(1-rho),Lq=rho*rho/(1-rho),W=1/(mu-lambda),Wq=lambda/(mu*(mu-lambda));return{model:"mm1_queue",utilization:clean(rho),system_size:clean(L),queue_size:clean(Lq),system_time:clean(W),queue_time:clean(Wq)};}
function breakEven(args){const fixed=num(args.fixed_cost,"fixed_cost",{min:0,max:1e15}),price=num(args.unit_price,"unit_price",{min:-1e15,max:1e15}),variable=num(args.unit_variable_cost,"unit_variable_cost",{min:-1e15,max:1e15}),margin=price-variable;if(margin<=0)err("NON_POSITIVE_CONTRIBUTION_MARGIN");const units=fixed/margin;return{model:"break_even",contribution_margin:clean(margin),break_even_units:clean(units),break_even_revenue:clean(units*price)};}
function blackScholes(args){const S=num(args.spot,"spot",{min:EPS,max:1e15}),K=num(args.strike,"strike",{min:EPS,max:1e15}),T=num(args.time_years,"time_years",{min:EPS,max:100}),r=num(args.rate,"rate",{min:-5,max:5}),sigma=num(args.volatility,"volatility",{min:EPS,max:10});const erf=x=>{const sign=x<0?-1:1,a=Math.abs(x),t=1/(1+0.3275911*a),y=1-(((((1.061405429*t-1.453152027)*t+1.421413741)*t-0.284496736)*t+0.254829592)*t)*Math.exp(-a*a);return sign*y},N=x=>0.5*(1+erf(x/Math.SQRT2)),d1=(Math.log(S/K)+(r+0.5*sigma*sigma)*T)/(sigma*Math.sqrt(T)),d2=d1-sigma*Math.sqrt(T),call=S*N(d1)-K*Math.exp(-r*T)*N(d2),put=K*Math.exp(-r*T)*N(-d2)-S*N(-d1);return{model:"black_scholes",call:clean(call),put:clean(put),d1:clean(d1),d2:clean(d2)};}

function locationFusion(args){
  const cells=arr(args.cells,"cells",300),keys=["population","poi","built","night","traffic","growth","competition"],defaultWeights={population:0.24,poi:0.16,built:0.14,night:0.16,traffic:0.12,growth:0.10,competition:0.08},rawWeights=args.weights&&typeof args.weights==="object"?args.weights:defaultWeights,ws=keys.map(k=>num(rawWeights[k],`weight_${k}`,{min:0,max:100,def:defaultWeights[k]})),weights=normalizeWeights(ws),vals={};
  for(const k of keys)vals[k]=cells.map((c,i)=>num(c[k],`${k}_${i}`,{min:0,max:1e15,def:0}));
  const ranges={};for(const k of keys){const a=vals[k],lo=Math.min(...a),hi=Math.max(...a);ranges[k]=[lo,hi]}
  const scored=cells.map((c,i)=>{let s=0;const parts={};for(let z=0;z<keys.length;z++){const k=keys[z],[lo,hi]=ranges[k],v=vals[k][i];let n=hi-lo<=EPS?0.5:(v-lo)/(hi-lo);if(k==="competition")n=1-n;const contribution=n*weights[z];s+=contribution;parts[k]={normalized:clean(n),weight:clean(weights[z]),contribution:clean(contribution)}}return{id:id(c.id,i),activity_score_0_100:clean(s*100),population:clean(vals.population[i]),components:parts}}).sort((a,b)=>b.activity_score_0_100-a.activity_score_0_100);
  let trade_area=null,diversionResult=null;
  if(cells.every(c=>Array.isArray(c.destinations)&&c.destinations.length)){const origins=cells.map((c,i)=>({id:id(c.id,i),demand:num(c.population??1,`population_${i}`,{min:0,max:1e12}),destinations:c.destinations}));trade_area=huff({origins,alpha:args.alpha,beta:args.beta});if(args.target_id)diversionResult=diversion({origins,alpha:args.alpha,beta:args.beta,target_id:args.target_id})}
  let syntheticOD=null;if(Array.isArray(args.destinations)&&Array.isArray(args.cost_matrix))syntheticOD=gravity({origins:cells.map((c,i)=>({id:id(c.id,i),mass:num(c.population??1,`population_${i}`,{min:0,max:1e12})})),destinations:args.destinations,cost_matrix:args.cost_matrix,beta:args.od_beta,destination_power:args.destination_power});
  return{model:"location_fusion",observed_lbs:false,calibrated:false,calibration_state:"deferred-until-benchmark-library",proxy_model:true,activity_cells:scored,trade_area,synthetic_od:syntheticOD,competitor_diversion:diversionResult,feature_weights:Object.fromEntries(keys.map((k,i)=>[k,clean(weights[i])]))};
}
function npvModel(args){const rate=num(args.discount_rate,"discount_rate",{min:-0.999,max:100}),flows=arr(args.cash_flows,"cash_flows").map((x,i)=>num(x,`cash_flow_${i}`,{min:-1e18,max:1e18}));let value=0;for(let t=0;t<flows.length;t++)value+=flows[t]/Math.pow(1+rate,t);return{model:"npv",discount_rate:rate,npv:clean(value),periods:flows.length-1};}
function irrModel(args){const flows=arr(args.cash_flows,"cash_flows").map((x,i)=>num(x,`cash_flow_${i}`,{min:-1e18,max:1e18}));if(!flows.some(x=>x<0)||!flows.some(x=>x>0))err("IRR_REQUIRES_SIGN_CHANGE");const f=r=>flows.reduce((s,x,t)=>s+x/Math.pow(1+r,t),0),lo=-0.999999,hi=num(args.max_rate,"max_rate",{min:0.01,max:1e6,def:100});let a=lo,fa=f(a),b=null,fb=null,prev=a,pf=fa;for(let i=1;i<=4000;i++){const x=lo+(hi-lo)*i/4000,y=f(x);if(pf===0){a=prev;b=prev;fb=0;break}if(y===0||pf*y<0){a=prev;fa=pf;b=x;fb=y;break}prev=x;pf=y}if(b===null)err("IRR_ROOT_NOT_BRACKETED",400,{max_rate:hi});if(a!==b)for(let i=0;i<120;i++){const m=(a+b)/2,fm=f(m);if(Math.abs(fm)<1e-10){a=b=m;break}if(fa*fm<=0){b=m;fb=fm}else{a=m;fa=fm}}const irr=(a+b)/2;return{model:"irr",irr:clean(irr),npv_at_irr:clean(f(irr))};}
function eoqModel(args){const D=num(args.annual_demand,"annual_demand",{min:0,max:1e18}),S=num(args.order_cost,"order_cost",{min:0,max:1e18}),H=num(args.holding_cost_per_unit_year,"holding_cost_per_unit_year",{min:EPS,max:1e18}),q=Math.sqrt(2*D*S/H);return{model:"eoq",economic_order_quantity:clean(q),orders_per_year:D>0?clean(D/q):0,cycle_inventory:clean(q/2)};}
function inventoryPolicy(args){const d=num(args.mean_demand_per_period,"mean_demand_per_period",{min:0,max:1e18}),sd=num(args.std_demand_per_period,"std_demand_per_period",{min:0,max:1e18}),lead=num(args.lead_time_periods,"lead_time_periods",{min:0,max:1e9}),z=num(args.service_z,"service_z",{min:0,max:8,def:1.645}),safety=z*sd*Math.sqrt(lead),rop=d*lead+safety;return{model:"inventory_policy",safety_stock:clean(safety),reorder_point:clean(rop),lead_time_demand:clean(d*lead),service_z:z};}
function historicalVarEs(args){const alpha=num(args.alpha,"alpha",{min:0.5,max:0.9999,def:0.95}),src=args.losses??(Array.isArray(args.returns)?args.returns.map(x=>-Number(x)):null),losses=arr(src,"losses",20000).map((x,i)=>num(x,`loss_${i}`,{min:-1e18,max:1e18})).sort((a,b)=>a-b),idx=Math.min(losses.length-1,Math.max(0,Math.ceil(alpha*losses.length)-1)),v=losses[idx],tail=losses.slice(idx),es=mean(tail);return{model:"historical_var_es",alpha,var:clean(v),expected_shortfall:clean(es),observations:losses.length,tail_observations:tail.length};}
function priceElasticity(args){const p1=num(args.price_1,"price_1",{min:EPS,max:1e18}),p2=num(args.price_2,"price_2",{min:EPS,max:1e18}),q1=num(args.quantity_1,"quantity_1",{min:EPS,max:1e18}),q2=num(args.quantity_2,"quantity_2",{min:EPS,max:1e18}),dp=(p2-p1)/((p1+p2)/2),dq=(q2-q1)/((q1+q2)/2);if(Math.abs(dp)<=EPS)err("ZERO_PRICE_CHANGE");return{model:"arc_price_elasticity",elasticity:clean(dq/dp),price_change_pct_midpoint:clean(dp),quantity_change_pct_midpoint:clean(dq)};}
function hhiModel(args){const raw=arr(args.shares,"shares",500).map((x,i)=>num(x,`share_${i}`,{min:0,max:100})),s=sum(raw);if(s<=EPS)err("ZERO_SHARE_SUM");const shares=raw.map(x=>x/s),hhi=sum(shares.map(x=>x*x))*10000;return{model:"hhi",hhi:clean(hhi),normalized_shares:shares.map(clean),concentration:hhi<1500?"unconcentrated":hhi<2500?"moderate":"high"};}
function creditExpectedLoss(args){const exposures=arr(args.exposures,"exposures",500).map((x,i)=>{const pd=num(x.pd,`pd_${i}`,{min:0,max:1}),lgd=num(x.lgd,`lgd_${i}`,{min:0,max:1}),ead=num(x.ead,`ead_${i}`,{min:0,max:1e18}),el=pd*lgd*ead;return{id:id(x.id,i),pd,lgd,ead,expected_loss:clean(el)}}),total=sum(exposures.map(x=>x.expected_loss));return{model:"credit_expected_loss",total_expected_loss:clean(total),exposures};}
function bassDiffusion(args){const market=num(args.market_size,"market_size",{min:EPS,max:1e18}),p=num(args.innovation,"innovation",{min:0,max:1}),q=num(args.imitation,"imitation",{min:0,max:10}),periods=Math.trunc(num(args.periods,"periods",{min:1,max:1000,def:24}));let cum=num(args.initial_adopters,"initial_adopters",{min:0,max:market,def:0});const rows=[];for(let t=1;t<=periods;t++){const adoption=Math.max(0,Math.min(market-cum,(p+q*(cum/market))*(market-cum)));cum+=adoption;rows.push({period:t,new_adopters:clean(adoption),cumulative_adopters:clean(cum),penetration:clean(cum/market)})}return{model:"bass_diffusion",market_size:market,innovation:p,imitation:q,series:rows};}
function sirModel(args){const N=num(args.population,"population",{min:EPS,max:1e18}),beta=num(args.beta,"beta",{min:0,max:100}),gamma=num(args.gamma,"gamma",{min:0,max:100}),days=Math.trunc(num(args.days,"days",{min:1,max:5000,def:120})),dt=num(args.dt,"dt",{min:0.001,max:1,def:0.25});let I=num(args.infected,"infected",{min:0,max:N,def:1}),R=num(args.recovered,"recovered",{min:0,max:N-I,def:0}),S=N-I-R;const out=[];let peak=I;for(let t=0;t<=days+EPS;t+=dt){if(Math.abs(t-Math.round(t))<dt/2)out.push({day:Math.round(t),susceptible:clean(S),infected:clean(I),recovered:clean(R)});const inf=beta*S*I/N,rec=gamma*I;S=Math.max(0,S-inf*dt);I=Math.max(0,I+(inf-rec)*dt);R=Math.min(N,R+rec*dt);peak=Math.max(peak,I)}return{model:"sir_local",peak_infected:clean(peak),series:out.slice(0,days+1)};}
function weibullPoint(args){const shape=num(args.shape,"shape",{min:EPS,max:1000}),scale=num(args.scale,"scale",{min:EPS,max:1e18}),t=num(args.time,"time",{min:0,max:1e18}),r=Math.exp(-Math.pow(t/scale,shape)),hazard=t===0&&shape<1?Infinity:(shape/scale)*Math.pow(Math.max(t,EPS)/scale,shape-1);return{model:"weibull_reliability_point",reliability:clean(r),failure_probability:clean(1-r),hazard:clean(hazard),shape,scale,time:t};}
function faultTree(args){const events=arr(args.events,"events",200).map((x,i)=>({id:id(x.id,i),p:num(x.probability,`probability_${i}`,{min:0,max:1})})),gate=String(args.gate||"OR").toUpperCase();if(!["AND","OR"].includes(gate))err("INVALID_GATE");const p=gate==="AND"?events.reduce((s,x)=>s*x.p,1):1-events.reduce((s,x)=>s*(1-x.p),1);return{model:"fault_tree_independent",gate,top_event_probability:clean(p),assumption:"independent-basic-events",events};}
function pertSchedule(args){const tasks=arr(args.tasks,"tasks",200).map((x,i)=>{const tid=id(x.id,i),o=num(x.optimistic??x.duration,`optimistic_${i}`,{min:0,max:1e9}),m=num(x.most_likely??x.duration,`most_likely_${i}`,{min:0,max:1e9}),p=num(x.pessimistic??x.duration,`pessimistic_${i}`,{min:0,max:1e9});if(!(o<=m&&m<=p))err("INVALID_PERT_ORDER",400,{task_id:tid});return{id:tid,deps:Array.isArray(x.dependencies)?x.dependencies.map(String):[],duration:(o+4*m+p)/6,variance:Math.pow((p-o)/6,2)}}),map=new Map(tasks.map(x=>[x.id,x]));for(const t of tasks)for(const d of t.deps)if(!map.has(d))err("PERT_DEPENDENCY_NOT_FOUND",400,{task_id:t.id,dependency:d});const indeg=new Map(tasks.map(t=>[t.id,t.deps.length])),children=new Map(tasks.map(t=>[t.id,[]]));for(const t of tasks)for(const d of t.deps)children.get(d).push(t.id);const q=tasks.filter(t=>indeg.get(t.id)===0).map(t=>t.id),order=[];while(q.length){const x=q.shift();order.push(x);for(const c of children.get(x)){indeg.set(c,indeg.get(c)-1);if(indeg.get(c)===0)q.push(c)}}if(order.length!==tasks.length)err("PERT_CYCLE");const ef=new Map(),pred=new Map(),rows=[];for(const tid of order){const t=map.get(tid);let best=0,bp=null;for(const d of t.deps){if((ef.get(d)||0)>best){best=ef.get(d);bp=d}}const finish=best+t.duration;ef.set(tid,finish);pred.set(tid,bp);rows.push({id:tid,expected_duration:clean(t.duration),variance:clean(t.variance),earliest_start:clean(best),earliest_finish:clean(finish)})}let end=rows.reduce((a,b)=>a.earliest_finish>b.earliest_finish?a:b),path=[];for(let x=end?.id;x;x=pred.get(x))path.push(x);path.reverse();return{model:"pert_schedule",project_expected_duration:end?.earliest_finish||0,critical_path:path,tasks:rows};}
function kelly(args){const p=num(args.win_probability,"win_probability",{min:0,max:1}),b=num(args.net_win_multiple,"net_win_multiple",{min:EPS,max:1e9}),q=1-p,f=(b*p-q)/b;return{model:"kelly_fraction",raw_fraction:clean(f),recommended_nonnegative_fraction:clean(Math.max(0,f)),win_probability:p,net_win_multiple:b};}

export const LOCAL_MODELS=Object.freeze({three_ring_trade_area:threeRing,huff_trade_area:huff,gravity_od:gravity,competitor_diversion:diversion,accessibility_score:accessibility,weighted_index:weightedIndex,bayesian_evidence_fusion:bayesEvidence,weighted_decision:weightedDecision,expected_value:expectedValue,entropy,markov_chain:markov,pagerank:pageRank,threshold_diffusion:thresholdDiffusion,prospect_value:prospect,mm1_queue:mm1,break_even:breakEven,black_scholes:blackScholes,location_fusion:locationFusion,npv:npvModel,irr:irrModel,eoq:eoqModel,inventory_policy:inventoryPolicy,historical_var_es:historicalVarEs,arc_price_elasticity:priceElasticity,hhi:hhiModel,credit_expected_loss:creditExpectedLoss,bass_diffusion:bassDiffusion,sir_local:sirModel,weibull_reliability_point:weibullPoint,fault_tree_independent:faultTree,pert_schedule:pertSchedule,kelly_fraction:kelly});
export function localModelMeta(){return{provider:"local-model",arbitrary_code:false,heavy_compute:false,model_ids:Object.keys(LOCAL_MODELS),limits:{max_items:MAX_ITEMS,max_matrix:MAX_MATRIX},calibration_state:"deferred-until-benchmark-library"}}
export function runLocalModel(modelId,args={}){const fn=LOCAL_MODELS[String(modelId||"")];if(!fn)err("UNKNOWN_MODEL",400,{allowed:Object.keys(LOCAL_MODELS)});return fn(args||{})}
