const MAX_ITEMS=500,MAX_MATRIX=120,EPS=1e-12;
const err=(m,status=400,details)=>{throw Object.assign(new Error(m),{status,details})};
const num=(v,name,{min=-Infinity,max=Infinity,def}={})=>{const n=Number(v);if(!Number.isFinite(n)){if(def!==undefined)return def;err(`INVALID_${name.toUpperCase()}`)}if(n<min||n>max)err(`INVALID_${name.toUpperCase()}`,400,{min,max});return n};
const arr=(v,name,max=MAX_ITEMS)=>{if(!Array.isArray(v)||v.length===0||v.length>max)err(`INVALID_${name.toUpperCase()}`,400,{max});return v};
const id=(v,i)=>String(v??i).slice(0,96);
const clean=(n)=>Number.isFinite(n)?Number(n.toFixed(12)):null;
const sum=a=>a.reduce((s,x)=>s+x,0);
const mean=a=>sum(a)/Math.max(1,a.length);
function normalizeWeights(weights){const w=arr(weights,"weights").map((x,i)=>num(typeof x==="object"?x.weight:x,`weight_${i}`,{min:0,max:1e9})),s=sum(w);if(s<=EPS)err("ZERO_WEIGHT_SUM");return w.map(x=>x/s)}

function threeRing(args){
  const items=arr(args.items,"items").map((x,i)=>({id:id(x.id,i),travel_time:num(x.travel_time??x.minutes,`travel_time_${i}`,{min:0,max:1440}),demand:num(x.demand??x.population??1,`demand_${i}`,{min:0,max:1e12}),attraction:num(x.attraction??1,`attraction_${i}`,{min:0,max:1e12})}));
  const t1=num(args.core_minutes,"core_minutes",{min:1,max:240,def:10}),t2=num(args.secondary_minutes,"secondary_minutes",{min:t1,max:480,def:Math.max(20,t1)}),t3=num(args.fringe_minutes,"fringe_minutes",{min:t2,max:720,def:Math.max(30,t2)});
  const rings={core:[],secondary:[],fringe:[],outside:[]};
  for(const x of items){const r=x.travel_time<=t1?"core":x.travel_time<=t2?"secondary":x.travel_time<=t3?"fringe":"outside";rings[r].push(x)}
  const metrics={};for(const[k,v]of Object.entries(rings))metrics[k]={cells:v.length,demand:clean(sum(v.map(x=>x.demand))),weighted_attraction:clean(sum(v.map(x=>x.demand*x.attraction)))};
  return{model:"three_ring_trade_area",thresholds_minutes:[t1,t2,t3],rings,metrics};
}
function huff(args){
  const origins=arr(args.origins,"origins",200),alpha=num(args.alpha,"alpha",{min:0.01,max:10,def:1}),beta=num(args.beta,"beta",{min:0.01,max:10,def:2});
  const rows=origins.map((o,oi)=>{const demand=num(o.demand??o.population??1,`demand_${oi}`,{min:0,max:1e12}),choices=arr(o.destinations,`destinations_${oi}`,80).map((d,di)=>{const a=num(d.attraction??d.size??1,`attraction_${oi}_${di}`,{min:0,max:1e12}),c=num(d.cost??d.travel_time??d.distance,`cost_${oi}_${di}`,{min:0.001,max:1e9});return{id:id(d.id,di),score:Math.pow(Math.max(a,EPS),alpha)/Math.pow(c,beta)}});const den=sum(choices.map(x=>x.score));if(den<=EPS)err("HUFF_ZERO_DENOMINATOR");return{id:id(o.id,oi),demand,probabilities:choices.map(x=>({id:x.id,probability:clean(x.score/den),expected_flow:clean(demand*x.score/den)}))}});
  const totals={};for(const r of rows)for(const p of r.probabilities)totals[p.id]=(totals[p.id]||0)+p.expected_flow;
  return{model:"huff_trade_area",alpha,beta,origins:rows,destination_expected_flow:Object.fromEntries(Object.entries(totals).map(([k,v])=>[k,clean(v)]))};
}
function gravity(args){
  const origins=arr(args.origins,"origins",MAX_MATRIX),destinations=arr(args.destinations,"destinations",MAX_MATRIX);if(origins.length*destinations.length>5000)err("MATRIX_TOO_LARGE",413,{max_cells:5000});
  const beta=num(args.beta,"beta",{min:0.000001,max:50,def:0.1}),power=num(args.destination_power,"destination_power",{min:0,max:5,def:1}),costs=arr(args.cost_matrix,"cost_matrix",MAX_MATRIX);if(costs.length!==origins.length)err("COST_MATRIX_SHAPE_MISMATCH");
  const dest=destinations.map((d,j)=>({id:id(d.id,j),mass:num(d.mass??d.attraction??1,`destination_mass_${j}`,{min:0,max:1e12})}));
  const rows=[];const destTotals=Object.fromEntries(dest.map(x=>[x.id,0]));
  for(let i=0;i<origins.length;i++){const o=origins[i],mass=num(o.mass??o.population??o.demand??1,`origin_mass_${i}`,{min:0,max:1e12}),row=costs[i];if(!Array.isArray(row)||row.length!==dest.length)err("COST_MATRIX_SHAPE_MISMATCH");const scores=dest.map((d,j)=>{const c=num(row[j],`cost_${i}_${j}`,{min:0,max:1e9});return Math.pow(Math.max(d.mass,EPS),power)*Math.exp(-beta*c)}),den=sum(scores);if(den<=EPS)err("GRAVITY_ZERO_DENOMINATOR");const flows=dest.map((d,j)=>{const f=mass*scores[j]/den;destTotals[d.id]+=f;return{id:d.id,cost:row[j],flow:clean(f)}});rows.push({id:id(o.id,i),mass,flows})}
  return{model:"gravity_od",beta,destination_power:power,origins:rows,destination_flow:Object.fromEntries(Object.entries(destTotals).map(([k,v])=>[k,clean(v)]))};
}
function diversion(args){
  const base=huff(args),target=String(args.target_id||"");if(!target)err("ARG_REQUIRED:target_id");
  const diversion={};let targetFlow=0;
  for(const r of base.origins){const tp=r.probabilities.find(x=>x.id===target);if(!tp)continue;targetFlow+=tp.expected_flow;const others=r.probabilities.filter(x=>x.id!==target),den=sum(others.map(x=>x.probability));if(den<=EPS)continue;for(const p of others)diversion[p.id]=(diversion[p.id]||0)+tp.expected_flow*(p.probability/den)}
  return{model:"competitor_diversion",target_id:target,target_expected_flow:clean(targetFlow),diverted_to:Object.fromEntries(Object.entries(diversion).map(([k,v])=>[k,clean(v)])),baseline:base.destination_expected_flow};
}
function accessibility(args){
  const opportunities=arr(args.opportunities,"opportunities"),beta=num(args.beta,"beta",{min:0.000001,max:50,def:0.1}),power=num(args.power,"power",{min:0.01,max:10,def:1});let score=0;const parts=[];
  for(let i=0;i<opportunities.length;i++){const x=opportunities[i],value=num(x.value??x.opportunities??1,`value_${i}`,{min:0,max:1e12}),cost=num(x.cost??x.travel_time??x.distance,`cost_${i}`,{min:0,max:1e9}),component=Math.pow(value,power)*Math.exp(-beta*cost);score+=component;parts.push({id:id(x.id,i),component:clean(component)})}
  return{model:"accessibility_score",beta,power,score:clean(score),components:parts};
}
function weightedIndex(args){
  const features=arr(args.features,"features"),weights=normalizeWeights(features.map(x=>x.weight??1));let score=0;const components=features.map((x,i)=>{const value=num(x.value,`value_${i}`,{min:-1e12,max:1e12}),min=num(x.min,`min_${i}`,{def:0}),max=num(x.max,`max_${i}`,{def:1});if(max<=min)err("INVALID_FEATURE_RANGE",400,{index:i});let z=(value-min)/(max-min);z=Math.max(0,Math.min(1,z));if(x.direction==="negative")z=1-z;const c=z*weights[i];score+=c;return{id:id(x.id,i),normalized:clean(z),weight:clean(weights[i]),contribution:clean(c)}});return{model:"weighted_index",score_0_100:clean(score*100),components};
}
function bayesEvidence(args){
  let prior=num(args.prior_probability,"prior_probability",{min:0.000001,max:0.999999,def:0.5}),odds=prior/(1-prior);const evidence=arr(args.evidence,"evidence").map((e,i)=>{let lr;if(e.likelihood_ratio!==undefined)lr=num(e.likelihood_ratio,`likelihood_ratio_${i}`,{min:0.000001,max:1e9});else{const ph=num(e.p_if_h,`p_if_h_${i}`,{min:0.000001,max:0.999999}),pn=num(e.p_if_not_h,`p_if_not_h_${i}`,{min:0.000001,max:0.999999});lr=ph/pn}odds*=lr;return{id:id(e.id,i),likelihood_ratio:clean(lr)}});const posterior=odds/(1+odds);return{model:"bayesian_evidence_fusion",prior_probability:prior,posterior_probability:clean(posterior),posterior_odds:clean(odds),evidence};
}
function weightedDecision(args){
  const criteria=arr(args.criteria,"criteria",100),weights=normalizeWeights(criteria.map(c=>c.weight??1)),options=arr(args.options,"options",100);const scored=options.map((o,oi)=>{const values=arr(o.values,`values_${oi}`,100);if(values.length!==criteria.length)err("DECISION_MATRIX_SHAPE_MISMATCH");let score=0;const parts=values.map((v,i)=>{const n=num(v,`value_${oi}_${i}`,{min:0,max:1}),c=n*weights[i];score+=c;return{criterion:id(criteria[i].id,i),value:n,contribution:clean(c)}});return{id:id(o.id,oi),score:clean(score),components:parts}}).sort((a,b)=>b.score-a.score);return{model:"weighted_decision",ranking:scored};
}
function expectedValue(args){const scenarios=arr(args.scenarios,"scenarios",200);let pSum=0,ev=0;const out=scenarios.map((s,i)=>{const p=num(s.probability,`probability_${i}`,{min:0,max:1}),v=num(s.value??s.payoff,`value_${i}`,{min:-1e15,max:1e15});pSum+=p;ev+=p*v;return{id:id(s.id,i),probability:p,value:v,contribution:clean(p*v)}});if(Math.abs(pSum-1)>1e-6)err("PROBABILITIES_MUST_SUM_TO_ONE",400,{sum:pSum});return{model:"expected_value",expected_value:clean(ev),scenarios:out};}
function entropy(args){const probs=arr(args.probabilities,"probabilities",MAX_ITEMS).map((p,i)=>num(p,`probability_${i}`,{min:0,max:1})),s=sum(probs);if(Math.abs(s-1)>1e-6)err("PROBABILITIES_MUST_SUM_TO_ONE",400,{sum:s});let h=0;for(const p of probs)if(p>0)h-=p*Math.log2(p);return{model:"entropy",bits:clean(h),normalized:clean(h/Math.log2(probs.length))};}
function markov(args){const matrix=arr(args.transition_matrix,"transition_matrix",MAX_MATRIX),n=matrix.length;if(n>MAX_MATRIX)err("MATRIX_TOO_LARGE");for(let i=0;i<n;i++){if(!Array.isArray(matrix[i])||matrix[i].length!==n)err("TRANSITION_MATRIX_SHAPE_MISMATCH");const r=matrix[i].map((x,j)=>num(x,`transition_${i}_${j}`,{min:0,max:1}));if(Math.abs(sum(r)-1)>1e-6)err("TRANSITION_ROW_MUST_SUM_TO_ONE",400,{row:i});matrix[i]=r}let state=arr(args.initial_state,"initial_state",MAX_MATRIX).map((x,i)=>num(x,`initial_${i}`,{min:0,max:1}));if(state.length!==n||Math.abs(sum(state)-1)>1e-6)err("INITIAL_STATE_INVALID");const steps=Math.trunc(num(args.steps,"steps",{min:1,max:1000,def:1}));for(let k=0;k<steps;k++){const next=Array(n).fill(0);for(let i=0;i<n;i++)for(let j=0;j<n;j++)next[j]+=state[i]*matrix[i][j];state=next}return{model:"markov_chain",steps,state:state.map(clean)};}
function pageRank(args){const nodes=arr(args.nodes,"nodes",200).map((x,i)=>id(typeof x==="object"?x.id:x,i)),index=new Map(nodes.map((x,i)=>[x,i])),n=nodes.length,edges=arr(args.edges,"edges",1000),d=num(args.damping,"damping",{min:0.1,max:0.99,def:0.85}),iters=Math.trunc(num(args.iterations,"iterations",{min:1,max:200,def:50}));const out=Array(n).fill(0).map(()=>[]);for(const e of edges){const a=index.get(String(e.source)),b=index.get(String(e.target));if(a===undefined||b===undefined)err("EDGE_NODE_NOT_FOUND");out[a].push(b)}let r=Array(n).fill(1/n);for(let k=0;k<iters;k++){const next=Array(n).fill((1-d)/n);let dangling=0;for(let i=0;i<n;i++){if(!out[i].length){dangling+=r[i];continue}const share=d*r[i]/out[i].length;for(const j of out[i])next[j]+=share}const add=d*dangling/n;for(let i=0;i<n;i++)next[i]+=add;r=next}return{model:"pagerank",scores:nodes.map((x,i)=>({id:x,score:clean(r[i])})).sort((a,b)=>b.score-a.score)};}
function thresholdDiffusion(args){const nodes=arr(args.nodes,"nodes",300).map((x,i)=>({id:id(typeof x==="object"?x.id:x,i),threshold:num(typeof x==="object"?x.threshold:args.threshold,`threshold_${i}`,{min:0,max:1,def:0.5})})),idx=new Map(nodes.map((x,i)=>[x.id,i])),edges=arr(args.edges,"edges",1500),adj=Array(nodes.length).fill(0).map(()=>[]);for(const e of edges){const a=idx.get(String(e.source)),b=idx.get(String(e.target));if(a===undefined||b===undefined)err("EDGE_NODE_NOT_FOUND");adj[a].push(b);if(e.directed!==true)adj[b].push(a)}const active=new Set(arr(args.seeds,"seeds",300).map(String));for(const s of active)if(!idx.has(s))err("SEED_NODE_NOT_FOUND");const maxSteps=Math.trunc(num(args.max_steps,"max_steps",{min:1,max:100,def:20}));const history=[active.size];for(let step=0;step<maxSteps;step++){const add=[];for(let i=0;i<nodes.length;i++){const node=nodes[i];if(active.has(node.id)||adj[i].length===0)continue;const frac=adj[i].filter(j=>active.has(nodes[j].id)).length/adj[i].length;if(frac>=node.threshold)add.push(node.id)}if(!add.length)break;for(const x of add)active.add(x);history.push(active.size)}return{model:"threshold_diffusion",active_count:active.size,active:[...active],history};}
function prospect(args){const x=num(args.outcome,"outcome",{min:-1e15,max:1e15}),reference=num(args.reference,"reference",{min:-1e15,max:1e15,def:0}),alpha=num(args.alpha,"alpha",{min:0.01,max:2,def:0.88}),beta=num(args.beta,"beta",{min:0.01,max:2,def:0.88}),lambda=num(args.loss_aversion,"loss_aversion",{min:0,max:20,def:2.25}),d=x-reference,value=d>=0?Math.pow(d,alpha):-lambda*Math.pow(-d,beta);return{model:"prospect_value",outcome:x,reference,value:clean(value)};}
function mm1(args){const lambda=num(args.arrival_rate,"arrival_rate",{min:0,max:1e12}),mu=num(args.service_rate,"service_rate",{min:EPS,max:1e12});if(lambda>=mu)err("QUEUE_UNSTABLE",400,{requirement:"arrival_rate < service_rate"});const rho=lambda/mu,L=rho/(1-rho),Lq=rho*rho/(1-rho),W=1/(mu-lambda),Wq=lambda/(mu*(mu-lambda));return{model:"mm1_queue",utilization:clean(rho),system_size:clean(L),queue_size:clean(Lq),system_time:clean(W),queue_time:clean(Wq)};}
function breakEven(args){const fixed=num(args.fixed_cost,"fixed_cost",{min:0,max:1e15}),price=num(args.unit_price,"unit_price",{min:-1e15,max:1e15}),variable=num(args.unit_variable_cost,"unit_variable_cost",{min:-1e15,max:1e15}),margin=price-variable;if(margin<=0)err("NON_POSITIVE_CONTRIBUTION_MARGIN");const units=fixed/margin;return{model:"break_even",contribution_margin:clean(margin),break_even_units:clean(units),break_even_revenue:clean(units*price)};}
function blackScholes(args){const S=num(args.spot,"spot",{min:EPS,max:1e15}),K=num(args.strike,"strike",{min:EPS,max:1e15}),T=num(args.time_years,"time_years",{min:EPS,max:100}),r=num(args.rate,"rate",{min:-5,max:5}),sigma=num(args.volatility,"volatility",{min:EPS,max:10});const erf=x=>{const sign=x<0?-1:1,a=Math.abs(x),t=1/(1+0.3275911*a),y=1-(((((1.061405429*t-1.453152027)*t+1.421413741)*t-0.284496736)*t+0.254829592)*t)*Math.exp(-a*a);return sign*y},N=x=>0.5*(1+erf(x/Math.SQRT2)),d1=(Math.log(S/K)+(r+0.5*sigma*sigma)*T)/(sigma*Math.sqrt(T)),d2=d1-sigma*Math.sqrt(T),call=S*N(d1)-K*Math.exp(-r*T)*N(d2),put=K*Math.exp(-r*T)*N(-d2)-S*N(-d1);return{model:"black_scholes",call:clean(call),put:clean(put),d1:clean(d1),d2:clean(d2)};}

export const LOCAL_MODELS=Object.freeze({three_ring_trade_area:threeRing,huff_trade_area:huff,gravity_od:gravity,competitor_diversion:diversion,accessibility_score:accessibility,weighted_index:weightedIndex,bayesian_evidence_fusion:bayesEvidence,weighted_decision:weightedDecision,expected_value:expectedValue,entropy,markov_chain:markov,pagerank:pageRank,threshold_diffusion:thresholdDiffusion,prospect_value:prospect,mm1_queue:mm1,break_even:breakEven,black_scholes:blackScholes});
export function localModelMeta(){return{provider:"local-model",arbitrary_code:false,heavy_compute:false,model_ids:Object.keys(LOCAL_MODELS),limits:{max_items:MAX_ITEMS,max_matrix:MAX_MATRIX}}}
export function runLocalModel(modelId,args={}){const fn=LOCAL_MODELS[String(modelId||"")];if(!fn)err("UNKNOWN_MODEL",400,{allowed:Object.keys(LOCAL_MODELS)});return fn(args||{})}
