const ENDPOINT="https://api.wolframalpha.com/v2/query";
const TIMEOUT_MS=15000,MAX_RESPONSE_BYTES=1000000,MAX_INPUT_CHARS=2000;
const text=(v,n)=>String(v??"").trim().slice(0,n);
function appId(env){const v=String(env?.WOLFRAM_APP_ID||"").trim();if(!v)throw Object.assign(new Error("WOLFRAM_APP_ID_NOT_CONFIGURED"),{status:503});return v}
async function readBounded(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_RESPONSE_BYTES)throw Object.assign(new Error("WOLFRAM_RESPONSE_TOO_LARGE"),{status:502});if(!r.body)return"";const reader=r.body.getReader(),chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_RESPONSE_BYTES){await reader.cancel().catch(()=>{});throw Object.assign(new Error("WOLFRAM_RESPONSE_TOO_LARGE"),{status:502})}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const all=new Uint8Array(total);let off=0;for(const c of chunks){all.set(c,off);off+=c.byteLength}return new TextDecoder().decode(all)}
function normalizeInput(v){const q=String(v??"").trim();if(!q)throw Object.assign(new Error("WOLFRAM_INPUT_REQUIRED"),{status:400});if(q.length>MAX_INPUT_CHARS)throw Object.assign(new Error("WOLFRAM_INPUT_TOO_LONG"),{status:400});return q}
function compact(body){const q=body?.queryresult||{},pods=Array.isArray(q.pods)?q.pods.slice(0,16).map(p=>({id:text(p?.id,120),title:text(p?.title,200),scanner:text(p?.scanner,100),primary:p?.primary===true,subpods:(Array.isArray(p?.subpods)?p.subpods:[]).slice(0,8).map(s=>({title:text(s?.title,160),plaintext:text(s?.plaintext,6000)}))})):[];return{success:q.success===true,error:q.error===true,numpods:Number(q.numpods||pods.length),datatypes:text(q.datatypes,500),timing:Number(q.timing||0),timedout:text(q.timedout,500),pods,assumptions:q.assumptions||undefined,didyoumeans:q.didyoumeans||undefined,warnings:q.warnings||undefined}}
export function wolframMeta(){return{provider:"wolfram-alpha",role:"symbolic-computational-knowledge",integration:"official-full-results-api-v2",endpoint:ENDPOINT,auth:"appid",secret_name:"WOLFRAM_APP_ID",arbitrary_url:false,arbitrary_code:false,input_limit_chars:MAX_INPUT_CHARS,response_limit_bytes:MAX_RESPONSE_BYTES,route_eligible:true}}
export async function queryWolfram(env,input,{units="metric"}={}){const q=normalizeInput(input),u=new URL(ENDPOINT);u.searchParams.set("appid",appId(env));u.searchParams.set("input",q);u.searchParams.set("output","json");u.searchParams.set("format","plaintext");u.searchParams.set("units",units==="nonmetric"?"nonmetric":"metric");u.searchParams.set("reinterpret","true");u.searchParams.set("totaltimeout","10");const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(u,{method:"GET",headers:{accept:"application/json"},signal:c.signal}),raw=await readBounded(r);let body=null;try{body=raw?JSON.parse(raw):null}catch{throw Object.assign(new Error("WOLFRAM_BAD_JSON"),{status:502})}if(!r.ok)throw Object.assign(new Error(r.status===401||r.status===403?"WOLFRAM_AUTH_FAILED":"WOLFRAM_UPSTREAM_HTTP_ERROR"),{status:r.status===401||r.status===403?503:502,details:{http_status:r.status}});return{provider:"wolfram-alpha",query:q,result:compact(body)}}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("WOLFRAM_TIMEOUT"),{status:504});throw e}finally{clearTimeout(t)}}
export async function probeWolfram(env){const configured=Boolean(String(env?.WOLFRAM_APP_ID||"").trim());if(!configured)return{ok:false,provider:"wolfram-alpha",configured:false,authenticated:false,computation_ok:false,secret_echo:false};try{const out=await queryWolfram(env,"2+2"),texts=(out.result?.pods||[]).flatMap(p=>(p.subpods||[]).map(s=>String(s.plaintext||""))),computationOk=out.result?.success===true&&texts.some(x=>/\b4\b/.test(x));return{ok:computationOk,provider:"wolfram-alpha",configured:true,authenticated:true,computation_ok:computationOk,api_success:out.result?.success===true,secret_echo:false}}catch(e){return{ok:false,provider:"wolfram-alpha",configured:true,authenticated:false,computation_ok:false,error_class:String(e?.message||"WOLFRAM_PROBE_FAILED"),http_status:Number(e?.details?.http_status||e?.status||0)||null,secret_echo:false}}}
